"use client";

import { useRouter } from "next/navigation";
import { useState, type FormEvent } from "react";
import { Loader2, ShieldCheck } from "lucide-react";
import { PasswordStrengthMeter } from "@/components/auth/password-strength";

export function AdminInvitationForm({ token, email }: { token: string; email: string }) {
  const router = useRouter(); const [name,setName]=useState(""); const [password,setPassword]=useState(""); const [confirm,setConfirm]=useState(""); const [error,setError]=useState<string|null>(null); const [loading,setLoading]=useState(false);
  const submit=async(event:FormEvent)=>{event.preventDefault();if(password!==confirm){setError("Пароли не совпадают");return;}setLoading(true);setError(null);const response=await fetch("/api/admin/invitations/accept",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({token,password,name})});if(!response.ok){const data=await response.json().catch(()=>null) as {error?:string}|null;setError(data?.error??"Не удалось принять приглашение");setLoading(false);return;}router.replace("/admin");router.refresh();};
  return <main className="grid min-h-dvh place-items-center px-4 py-10"><form onSubmit={submit} className="w-full max-w-md rounded-3xl border border-slate-700 bg-slate-900 p-7 shadow-2xl"><ShieldCheck className="size-9 text-blue-400"/><h1 className="mt-4 text-2xl font-semibold">Создание администратора</h1><p className="mt-2 text-sm text-slate-400">Email назначен приглашением и не может быть изменён.</p><label className="mt-6 grid gap-2 text-sm">Корпоративный email<input disabled value={email} className="h-11 rounded-xl border border-slate-700 bg-slate-950 px-3 text-slate-500"/></label><label className="mt-4 grid gap-2 text-sm">Имя<input value={name} onChange={(e)=>setName(e.target.value)} className="h-11 rounded-xl border border-slate-700 bg-slate-950 px-3"/></label><label className="mt-4 grid gap-2 text-sm">Пароль<input required type="password" autoComplete="new-password" value={password} onChange={(e)=>setPassword(e.target.value)} className="h-11 rounded-xl border border-slate-700 bg-slate-950 px-3"/></label><PasswordStrengthMeter password={password} className="mt-2"/><label className="mt-4 grid gap-2 text-sm">Повторите пароль<input required type="password" autoComplete="new-password" value={confirm} onChange={(e)=>setConfirm(e.target.value)} className="h-11 rounded-xl border border-slate-700 bg-slate-950 px-3"/></label>{error?<p role="alert" className="mt-4 rounded-xl bg-red-500/10 p-3 text-sm text-red-300">{error}</p>:null}<button disabled={loading} className="mt-6 flex h-11 w-full items-center justify-center gap-2 rounded-xl bg-blue-500 font-semibold text-white disabled:opacity-60">{loading?<Loader2 className="size-4 animate-spin"/>:null}Сохранить и войти</button></form></main>;
}
