"use client";

import { Loader2, MailPlus, X } from "lucide-react";
import { useState, type FormEvent } from "react";
import { cn } from "@/lib/utils";
import { TimezoneSelect } from "@/components/ui/timezone-select";
import { date, td, th, type AdminItem } from "./admin-types";
import { PasswordStrengthMeter } from "@/components/auth/password-strength";

async function apiError(response:Response){const payload=await response.json().catch(()=>null) as {error?:string}|null;return payload?.error??"Не удалось выполнить операцию";}

export function AdminAdministrators({items,onRefresh}:{items:AdminItem[];onRefresh:()=>Promise<void>}){
  const [email,setEmail]=useState("");const [sending,setSending]=useState(false);const [notice,setNotice]=useState<string|null>(null);const [selected,setSelected]=useState<AdminItem|null>(null);
  const invite=async(event:FormEvent)=>{event.preventDefault();setSending(true);setNotice(null);const response=await fetch("/api/admin/invitations",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({email})});if(response.ok){setEmail("");setNotice("Приглашение отправлено на корпоративный email");}else setNotice(await apiError(response));setSending(false);};
  return <div className="space-y-5"><form onSubmit={invite} className="flex max-w-2xl flex-wrap items-end gap-2 rounded-2xl border border-orange-500/20 bg-orange-500/10 p-4"><label className="min-w-64 flex-1 text-xs text-orange-100">Email нового администратора<input required type="email" value={email} onChange={(event)=>setEmail(event.target.value)} placeholder="admin@genora.art" className="mt-2 h-10 w-full rounded-xl border border-slate-700 bg-slate-950 px-3 text-sm text-white"/></label><button disabled={sending} className="flex h-10 items-center gap-2 rounded-xl bg-orange-500 px-4 text-xs font-semibold text-white disabled:opacity-60">{sending?<Loader2 className="size-4 animate-spin"/>:<MailPlus className="size-4"/>}Добавить администратора</button>{notice?<p className="w-full text-xs text-orange-200">{notice}</p>:null}</form><div className="overflow-x-auto rounded-2xl border border-slate-800 bg-slate-900/60"><table className="w-full min-w-[720px]"><thead><tr><th className={th}>Администратор</th><th className={th}>Защита</th><th className={th}>Статус</th><th className={th}>Последний вход</th></tr></thead><tbody>{items.map((item)=><tr key={item.id} onClick={()=>setSelected(item)} className="cursor-pointer hover:bg-slate-800/50"><td className={td}><b>{item.email}</b><br/><span className="text-slate-500">{item.nickname??item.name??"Без имени"}</span></td><td className={td}>{item.hasPin?"PIN включён":"Без PIN"} · {item.ipAllowlist.length?`${item.ipAllowlist.length} адресов`:"без белого списка"}</td><td className={td}>{item.active?"Активен":"Отключён"}</td><td className={td}>{date(item.lastLoginAt)}</td></tr>)}</tbody></table></div>{selected?<AdministratorPanel item={selected} onClose={()=>setSelected(null)} onSaved={async()=>{await onRefresh();setSelected(null);}}/>:null}</div>;
}

function AdministratorPanel({item,onClose,onSaved}:{item:AdminItem;onClose:()=>void;onSaved:()=>Promise<void>}){
  const [tab,setTab]=useState<"profile"|"security"|"password">("profile");const [name,setName]=useState(item.name??"");const [nickname,setNickname]=useState(item.nickname??"");const [timezone,setTimezone]=useState(item.timezone??"Europe/Minsk");const [pin,setPin]=useState("");const [clearPin,setClearPin]=useState(false);const [addresses,setAddresses]=useState(item.ipAllowlist.join("\n"));const [newPassword,setNewPassword]=useState("");const [currentPassword,setCurrentPassword]=useState("");const [saving,setSaving]=useState(false);const [message,setMessage]=useState<string|null>(null);
  const save=async(action:"profile"|"security"|"password")=>{setSaving(true);setMessage(null);const body=action==="profile"?{action,currentPassword,name,nickname,timezone}:action==="security"?{action,currentPassword,pin,clearPin,ipAllowlist:addresses.split(/\s|,/).filter(Boolean)}:{action,currentPassword,newPassword};const response=await fetch(`/api/admin/administrators/${item.id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify(body)});if(!response.ok){setMessage(await apiError(response));setSaving(false);return;}setMessage("Сохранено");setSaving(false);await onSaved();};
  return <div className="fixed inset-0 z-[60] flex justify-end bg-black/60" onMouseDown={(event)=>{if(event.currentTarget===event.target)onClose();}}><aside className="h-full w-full max-w-xl overflow-y-auto border-l border-slate-700 bg-slate-950 p-6"><div className="flex justify-between"><div><p className="text-xs uppercase text-orange-400">Администратор</p><h2 className="mt-1 text-xl font-semibold">{item.email}</h2></div><button onClick={onClose} aria-label="Закрыть" className="rounded-lg p-2 hover:bg-slate-800"><X className="size-4"/></button></div><div className="mt-5 flex gap-2">{(["profile","security","password"] as const).map((id)=><button key={id} onClick={()=>setTab(id)} className={cn("rounded-xl px-3 py-2 text-xs",tab===id?"bg-orange-500":"bg-slate-900 text-slate-400")}>{id==="profile"?"Профиль":id==="security"?"Безопасность":"Пароль"}</button>)}</div><div className="mt-5 space-y-4">{tab==="profile"?<><Field label="Имя" value={name} onChange={setName}/><Field label="Никнейм" value={nickname} onChange={setNickname}/><label className="grid gap-2 text-sm">Часовой пояс<TimezoneSelect value={timezone} onChange={setTimezone} label="Часовой пояс" searchLabel="Поиск часового пояса" emptyLabel="Часовой пояс не найден" locale="ru" className="border-slate-600 bg-white text-slate-900 hover:bg-slate-50"/></label></>:null}{tab==="security"?<><Field label="PIN, 4 цифры" value={pin} onChange={setPin} type="password"/><label className="flex gap-2 text-sm text-slate-300"><input type="checkbox" checked={clearPin} onChange={(event)=>setClearPin(event.target.checked)}/>Отключить текущий PIN</label><label className="grid gap-2 text-sm">Белый список IP/CIDR<textarea rows={6} value={addresses} onChange={(event)=>setAddresses(event.target.value)} placeholder={"203.0.113.10\n198.51.100.0/24"} className="rounded-xl border border-slate-700 bg-slate-900 p-3 text-sm"/></label><p className="text-xs text-amber-300">После сохранения вход будет разрешён только с указанных адресов.</p></>:null}{tab==="password"?<><Field label="Новый пароль" value={newPassword} onChange={setNewPassword} type="password"/><PasswordStrengthMeter password={newPassword}/></>:null}<Field label="Ваш текущий пароль — подтверждение операции" value={currentPassword} onChange={setCurrentPassword} type="password"/>{message?<p className="rounded-xl bg-slate-900 p-3 text-sm text-orange-300">{message}</p>:null}<button disabled={saving||!currentPassword} onClick={()=>void save(tab)} className="flex h-10 items-center gap-2 rounded-xl bg-orange-500 px-4 text-sm font-semibold disabled:opacity-50">{saving?<Loader2 className="size-4 animate-spin"/>:null}Сохранить</button></div></aside></div>;
}

function Field({label,value,onChange,type="text"}:{label:string;value:string;onChange:(value:string)=>void;type?:string}){return <label className="grid gap-2 text-sm">{label}<input type={type} value={value} onChange={(event)=>onChange(event.target.value)} className="h-10 rounded-xl border border-slate-700 bg-slate-900 px-3"/></label>}
