/* eslint-disable @next/next/no-img-element */
"use client";

import { DateRangeField } from "@/components/ui/date-range-field";
import { IS_STAGING } from "@/lib/site-env";
import { Gift, Loader2, UserRound, X } from "lucide-react";
import { useCallback, useEffect, useMemo, useState, type ReactNode } from "react";
import { MAX_ADMIN_BONUS_TOKENS, MIN_ADMIN_BONUS_TOKENS } from "@/lib/admin-bonus";
import { usdFromPaidTokens } from "@/lib/billing";
import { withCreditGlyphs } from "@/components/ui/credit-glyph";
import { formatTokensAsCredits } from "@/lib/credits";
import { cn } from "@/lib/utils";
import { date, money, number, tokens, td, th, type UserDetail } from "./admin-types";

type Tab = "profile" | "balance" | "usage" | "pnl" | "activity" | "welcome";
const tabLabels: Array<{ id: Tab; label: string }> = [
  { id: "profile", label: "Профиль" }, { id: "balance", label: "Баланс" },
  { id: "usage", label: "Использование" }, { id: "pnl", label: "P&L" }, { id: "activity", label: "Сессии и чаты" },
  ...(IS_STAGING ? [{ id: "welcome" as const, label: "Приветственный бонус" }] : []),
];
const kindLabels: Record<string, string> = { top_up: "Пополнение", usage: "Расход", adjustment: "Корректировка", bonus: "Бонус", refund: "Возврат" };

export function AdminUserPanel({ userId, onClose }: { userId: string; onClose: () => void }) {
  const [detail, setDetail] = useState<UserDetail | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [tab, setTab] = useState<Tab>("profile");
  const [changingStatus, setChangingStatus] = useState(false);
  const [bonusOpen, setBonusOpen] = useState(false);
  const [bonusAmount, setBonusAmount] = useState(MIN_ADMIN_BONUS_TOKENS);
  const [bonusBusy, setBonusBusy] = useState(false);
  const [bonusError, setBonusError] = useState<string | null>(null);
  const [from, setFrom] = useState(() => new Date(Date.now() - 30 * 86400_000).toISOString().slice(0, 10));
  const [to, setTo] = useState(() => new Date().toISOString().slice(0, 10));
  const [draftFrom, setDraftFrom] = useState(from);
  const [draftTo, setDraftTo] = useState(to);
  const fetchDetail = useCallback(async () => {
    const response = await fetch(`/api/admin/users/${userId}`, { cache: "no-store" });
    const payload = await response.json().catch(() => null) as UserDetail & { error?: string };
    if (!response.ok) throw new Error(payload?.error ?? "Не удалось загрузить пользователя");
    return payload;
  }, [userId]);
  useEffect(() => {
    let live = true;
    void fetchDetail().then((payload) => { if (live) setDetail(payload); }).catch((reason) => { if (live) setError(reason instanceof Error ? reason.message : "Ошибка загрузки"); });
    return () => { live = false; };
  }, [fetchDetail]);
  const pnl = useMemo(() => {
    const rows = (detail?.usage ?? []).filter((item) => item.createdAt.slice(0, 10) >= from && item.createdAt.slice(0, 10) <= to);
    const income = rows.reduce((sum, item) => sum + item.revenueUsd, 0);
    return { rows, income, cost: rows.reduce((sum, item) => sum + item.costUsd, 0) };
  }, [detail, from, to]);

  return <div className="fixed inset-0 z-50 flex justify-end bg-black/60" onMouseDown={(event) => { if (event.currentTarget === event.target) onClose(); }}>
    <aside className="h-full w-full max-w-4xl overflow-y-auto border-l border-slate-700 bg-slate-950 p-6 shadow-2xl">
      <div className="flex items-start justify-between"><div><p className="text-xs uppercase tracking-wider text-orange-400">Карточка пользователя</p><h2 className="mt-1 text-xl font-semibold">{detail?.user.email ?? "Загрузка…"}</h2></div><button aria-label="Закрыть" onClick={onClose} className="rounded-lg p-2 hover:bg-slate-800"><X className="size-4" /></button></div>
      {error ? <p className="mt-6 rounded-xl bg-red-500/10 p-3 text-sm text-red-300">{error}</p> : !detail ? <div className="grid h-80 place-items-center text-sm text-slate-500"><Loader2 className="size-5 animate-spin" /></div> : <>
        <div className="mt-6 flex items-center gap-4 rounded-2xl border border-slate-800 bg-slate-900/60 p-4">
          {detail.user.avatar_data_url ? <img src={detail.user.avatar_data_url} alt="" className="size-16 rounded-2xl object-cover" /> : <span className="grid size-16 place-items-center rounded-2xl bg-slate-800"><UserRound className="size-7 text-slate-500" /></span>}
          <div className="min-w-0"><p className="font-semibold">{detail.user.nickname ?? detail.user.name ?? "Без ника"}</p><p className="truncate text-sm text-slate-400">{detail.user.email}</p><p className="mt-1 text-xs text-slate-500">Создан: {date(detail.user.createdAt)}</p></div>
          <button type="button" onClick={() => setTab("balance")} className="ml-auto rounded-xl border border-emerald-700/35 bg-emerald-950/5 px-4 py-3 text-right text-emerald-900 dark:bg-emerald-500/10 dark:text-emerald-300"><span className="block text-[10px] font-semibold uppercase text-emerald-800 dark:text-emerald-300">Баланс</span><b className="text-lg">{withCreditGlyphs(formatTokensAsCredits(detail.user.balanceTokens, "ru", "spend"))}</b><span className="mt-1 block text-[11px] font-medium text-emerald-700 dark:text-emerald-400">{money(usdFromPaidTokens(detail.user.paidBalanceTokens ?? 0))}</span></button>
        </div>
        <div className="mt-4 flex flex-wrap items-center gap-2">{tabLabels.map((item) => <button key={item.id} onClick={() => setTab(item.id)} className={cn("rounded-xl px-3 py-2 text-xs", tab === item.id ? "bg-orange-500 text-white" : "bg-slate-900 text-slate-400 hover:text-white")}>{item.label}</button>)}<button type="button" onClick={() => { setBonusError(null); setBonusOpen(true); }} className="ml-auto inline-flex items-center gap-2 rounded-xl bg-emerald-500 px-4 py-2 text-xs font-semibold text-emerald-950 transition hover:bg-emerald-400"><Gift className="size-4" />Пополнить баланс</button></div>
        {tab === "profile" ? <section className="mt-5"><div className="grid gap-3 sm:grid-cols-2"><Info label="Ник" value={detail.user.nickname ?? "—"} /><Info label="Имя" value={detail.user.name ?? "—"} /><Info label="Email" value={detail.user.email} /><Info label="Статус" value={detail.user.status} /></div><button disabled={changingStatus} onClick={async () => { setChangingStatus(true); setError(null); const blocked = detail.user.status !== "blocked"; const response = await fetch(`/api/admin/users/${userId}`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ blocked }) }); if (response.ok) { const payload = await response.json() as { status: string }; setDetail({ ...detail, user: { ...detail.user, status: payload.status } }); } else { const payload = await response.json().catch(() => null) as { error?: string } | null; setError(payload?.error ?? "Не удалось изменить статус"); } setChangingStatus(false); }} className={cn("mt-4 rounded-xl px-4 py-2 text-sm font-semibold disabled:opacity-50", detail.user.status === "blocked" ? "bg-emerald-500/15 text-emerald-300" : "bg-red-500/15 text-red-300")}>{detail.user.status === "blocked" ? "Разблокировать пользователя" : "Заблокировать пользователя"}</button></section> : null}
        {tab === "balance" ? <Table><thead><tr><th className={th}>Дата</th><th className={th}>Операция</th><th className={th}>Токены</th><th className={th}>Платёж</th></tr></thead><tbody>{detail.transactions.map((item) => <tr key={item.id}><td className={td}>{date(item.createdAt)}</td><td className={td}>{item.kind === "bonus" ? <b>{item.note}</b> : <><b>{kindLabels[item.kind] ?? item.kind}</b><br /><span className="text-slate-500">{item.note.replace(/^Использование\s+/u, "").replace(/\s*[×x]\s*\d+(?:[.,]\d+)?\s*$/u, "")}</span></>}</td><td className={cn(td, item.tokenDelta >= 0 ? "text-emerald-400" : "text-amber-400")}>{withCreditGlyphs(tokens(item.tokenDelta, true))}</td><td className={td}>{item.amountUsd === null ? "—" : money(item.amountUsd)}</td></tr>)}</tbody></Table> : null}
        {tab === "usage" ? <Table><thead><tr><th className={th}>Дата</th><th className={th}>Модель</th><th className={th}>Списано</th><th className={th}>Себестоимость</th></tr></thead><tbody>{detail.usage.map((item) => { const failed = item.failed && item.billedTokens === 0 && item.costUsd === 0; const cell = cn(td, failed && "font-medium text-red-400"); return <tr key={item.id}><td className={cell}>{date(item.createdAt)}</td><td className={cell}>{item.model}<br /><span className={failed ? "text-red-400" : "text-slate-500"}>{item.chat_title || item.agent}</span></td><td className={cell}>{withCreditGlyphs(tokens(item.billedTokens))}</td><td className={cell}>{money(item.costUsd)}</td></tr>; })}</tbody></Table> : null}
        {tab === "pnl" ? <section className="mt-5"><div className="flex flex-wrap items-end gap-3 rounded-xl border border-slate-800 bg-slate-900/60 p-4"><DateRangeField from={draftFrom} to={draftTo} onFrom={setDraftFrom} onTo={setDraftTo} /><button type="button" disabled={!draftFrom || !draftTo} onClick={() => { const nextFrom = draftFrom <= draftTo ? draftFrom : draftTo; const nextTo = draftFrom <= draftTo ? draftTo : draftFrom; setDraftFrom(nextFrom); setDraftTo(nextTo); setFrom(nextFrom); setTo(nextTo); }} className="ml-auto h-10 rounded-xl bg-orange-600 px-5 text-xs font-semibold text-white shadow-sm hover:bg-orange-500 disabled:opacity-50">Применить</button><div className="ml-auto text-right text-xs text-slate-400"><p>Доход: <b className="text-emerald-400">{money(pnl.income)}</b></p><p>Себестоимость: <b className="text-amber-400">{money(pnl.cost)}</b></p><p>Профит: <b className={pnl.income - pnl.cost >= 0 ? "text-orange-400" : "text-red-400"}>{money(pnl.income - pnl.cost)}</b></p></div></div><Table><thead><tr><th className={th}>Дата и время</th><th className={th}>Чат</th><th className={th}>Доход</th><th className={th}>Себестоимость</th><th className={th}>Профит</th></tr></thead><tbody>{pnl.rows.map((item) => <tr key={item.id}><td className={td}>{date(item.createdAt)}</td><td className={td}>{item.chat_title}</td><td className={td}>{money(item.revenueUsd)}</td><td className={td}>{money(item.costUsd)}</td><td className={td}>{money(item.revenueUsd - item.costUsd)}</td></tr>)}</tbody></Table></section> : null}
        {tab === "activity" ? <div className="mt-5 grid gap-5 lg:grid-cols-2"><History title="Устройства">{detail.sessions.length ? detail.sessions.map((item) => <div key={item.session_ref} className="rounded-xl border border-slate-800 p-3 text-xs"><b>{item.user_agent ?? "Неизвестное устройство"}</b><p className="mt-1 text-slate-500">IP {item.ip_address ?? "—"} · {item.country_code ?? "—"}</p><p className="mt-1 text-slate-500">{date(item.lastSeenAt)}</p></div>) : <Empty />}</History><History title="Диалоги">{detail.conversations.length ? detail.conversations.map((item) => <div key={item.id} className="rounded-xl border border-slate-800 p-3 text-xs"><b>{item.title}</b><p className="mt-1 text-slate-500">{item.model_id ?? "Авто"} · {item.messageCount} сообщений</p><p className="mt-1 text-slate-500">{date(item.updatedAt)}</p></div>) : <Empty />}</History></div> : null}
        {tab === "welcome" ? <section className="mt-5 rounded-2xl border border-slate-800 bg-slate-900/60 p-4 text-sm text-slate-200">{detail.welcomeBonus ? <><p>Версия акции: {detail.welcomeBonus.version}</p><p className="mt-2">Будет начислено на 6-й день: <b className="text-emerald-300">{withCreditGlyphs(tokens(detail.welcomeBonus.earned))}</b> из {withCreditGlyphs(tokens(detail.welcomeBonus.total))}</p><ul className="mt-3 space-y-2 text-xs">{detail.welcomeBonus.tasks.map((task) => <li key={task.id} className="flex justify-between rounded-xl border border-slate-800 px-3 py-2"><span>{task.id}: {task.progress}/{task.required}</span><span>{withCreditGlyphs(tokens(task.earned, true))}</span></li>)}</ul></> : <p className="text-slate-500">Пользователь не участвует в текущей приветственной акции.</p>}</section> : null}
      </>}
      {bonusOpen ? <div className="fixed inset-0 z-[60] grid place-items-center bg-black/70 p-4" onMouseDown={(event) => { if (event.currentTarget === event.target && !bonusBusy) setBonusOpen(false); }}><form onSubmit={async (event) => { event.preventDefault(); setBonusError(null); if (!Number.isInteger(bonusAmount) || bonusAmount < MIN_ADMIN_BONUS_TOKENS || bonusAmount > MAX_ADMIN_BONUS_TOKENS) { setBonusError("Введите целое число от 5 до 1 000"); return; } setBonusBusy(true); try { const response = await fetch(`/api/admin/users/${userId}`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ action: "grant_bonus", tokenAmount: bonusAmount }) }); const payload = await response.json().catch(() => null) as { error?: string } | null; if (!response.ok) throw new Error(payload?.error ?? "Не удалось начислить бонус"); setDetail(await fetchDetail()); setTab("balance"); setBonusOpen(false); } catch (reason) { setBonusError(reason instanceof Error ? reason.message : "Не удалось начислить бонус"); } finally { setBonusBusy(false); } }} className="w-full max-w-md rounded-2xl border border-slate-700 bg-slate-950 p-5 shadow-2xl"><div className="flex items-start justify-between"><div><p className="text-xs font-semibold uppercase tracking-wider text-emerald-400">Бонус пользователю</p><h3 className="mt-1 text-lg font-semibold text-white">Пополнить баланс</h3><p className="mt-1 text-xs text-slate-400">Начисление появится в истории баланса как «Бонус».</p></div><button type="button" aria-label="Закрыть" disabled={bonusBusy} onClick={() => setBonusOpen(false)} className="rounded-lg p-2 text-slate-400 hover:bg-slate-800 hover:text-white disabled:opacity-50"><X className="size-4" /></button></div><label className="mt-5 grid gap-2 text-xs font-medium text-slate-300">Количество токенов<input autoFocus type="number" min={MIN_ADMIN_BONUS_TOKENS} max={MAX_ADMIN_BONUS_TOKENS} step="1" value={bonusAmount} onChange={(event) => setBonusAmount(event.target.valueAsNumber)} className="h-12 rounded-xl border border-slate-300 bg-white px-4 text-base font-semibold text-slate-950 outline-none focus:border-emerald-500 dark:border-slate-700 dark:bg-slate-900 dark:text-white" /></label><p className="mt-2 text-xs text-slate-500">Допустимо: от 5 до 1 000 токенов.</p>{bonusError ? <p className="mt-3 rounded-xl bg-red-500/10 p-3 text-xs text-red-300">{bonusError}</p> : null}<button type="submit" disabled={bonusBusy} className="mt-5 inline-flex h-11 w-full items-center justify-center gap-2 rounded-xl bg-emerald-500 text-sm font-semibold text-emerald-950 hover:bg-emerald-400 disabled:opacity-50">{bonusBusy ? <Loader2 className="size-4 animate-spin" /> : <Gift className="size-4" />}{bonusBusy ? "Начисляем…" : `Начислить ${number(Number.isFinite(bonusAmount) ? bonusAmount : 0)} токенов`}</button></form></div> : null}
    </aside>
  </div>;
}

function Info({ label, value }: { label: string; value: string }) { return <div className="rounded-xl border border-slate-800 bg-slate-900/60 p-4"><p className="text-[10px] uppercase text-slate-500">{label}</p><p className="mt-1 text-sm">{value}</p></div>; }
function History({ title, children }: { title: string; children: ReactNode }) { return <section><h3 className="mb-3 font-semibold">{title}</h3><div className="space-y-2">{children}</div></section>; }
function Empty() { return <p className="text-sm text-slate-500">Данных пока нет</p>; }
function Table({ children }: { children: ReactNode }) { return <div className="mt-5 overflow-x-auto rounded-2xl border border-slate-800 bg-slate-900/60"><table className="w-full min-w-[620px] border-collapse">{children}</table></div>; }
