import { IMAGE_AGENT_EXPANSION_IDS } from "@/lib/image-agent-expansions";

const COMPARE_AGENT_IDS = new Set([
  "background-removal",
  "background-replace",
  "gta-filter",
  "natural-retouch",
  "pro-headshot",
  "face-swap",
  "business-outfit",
  "privacy-redaction",
  "restore-old-photo",
  "remove-objects",
  "apply-tan",
  "remove-tattoo",
  "remove-makeup",
  "add-makeup",
  "change-eye-color",
  "plump-lips",
  "whiten-teeth",
  "remove-wrinkles",
  "add-cheekbones",
  "character-card",
  "kare",
  "bob",
  "cascade",
  "long-bob",
  "pixie",
  "shag",
  "undercut",
  "fade",
  "crop",
  "quiff",
  "pompadour",
  "caesar",
  "stubble",
  "short-boxed-beard",
  "full-beard",
  "goatee",
  "van-dyke",
  "ducktail",
  "bald",
  "remove-beard",
  "rain",
  "snow",
  "fog",
  "thunderstorm",
  "sun-rays",
  "overcast",
  "sunset",
  "business-suit-man",
  "business-suit-woman",
  "military-uniform",
  "police-uniform",
  "medical-uniform",
  "firefighter-uniform",
  "school-uniform",
  "pilot-uniform",
  "flight-attendant",
  "cowboy",
  "spider-man",
  "iron-man",
  "captain-america",
  "thor",
  "black-widow",
  "pirate",
  "medieval-knight",
  "samurai",
  "pharaoh",
  "venetian-carnival",
  "fantasy-mage",
  "vampire",
  "steampunk",
  "astronaut",
  "gladiator",
  "roman-legionary",
  "elf",
  "king",
  "queen",
  "rock-star",
  "santorini",
  "cappadocia",
  "dubai",
  "paris",
  "maldives",
  "iceland",
  "dolomites",
  "kyoto",
  "petra",
  "new-york",
  "bora-bora",
  "uyuni",
  "cartoon-hero",
  "caricature",
  "hero-3d",
  "drawn",
  "comic",
  "clay",
  "anime-hero",
  "fantasy",
  "pixel-illustration",
  "watercolor",
  "x-ray",
  "old-age",
  "fashion-caricature",
  "comic-2",
  ...IMAGE_AGENT_EXPANSION_IDS,
]);

const STILL_COVERS: Record<string, string> = {
  "honest-ai": "/agents/honest-ai.jpg",
  "contract-review": "/agents/contract-review.jpg",
  "decision-compare": "/agents/decision-compare.jpg",
  "med-helper": "/agents/med-helper.jpg",
  "video-promt": "/agents/video-promt.jpg",
  "photo-to-prompt": "/agents/photo-to-prompt.jpg",
  "customer-reply": "/agents/customer-reply.jpg",
  "code-review": "/agents/code-review.jpg",
  "sql-helper": "/agents/sql-helper.jpg",
  "copywriter": "/agents/copywriter.jpg",
  research: "/agents/research.jpg",
  "ads-brief": "/agents/ads-brief.jpg",
  translator: "/agents/translator.jpg",
  "logo-generator": "/agents/logo-generator.jpg",
  "business-card": "/agents/business-card.jpg",
  "brand-style-mini": "/agents/brand-style-mini.jpg",
  "family-photo": "/agents/family-photo-after.jpg",
  "combine-photos": "/agents/combine-photos-after.jpg",
  sunflowers: "/agents/sunflowers-after.jpg",
  "ai-character-card": "/agents/ai-character-card.jpg",
};

const COMPARE_COVERS: Record<string, { before: string; after: string }> = {
  "background-removal": { before: "/agents/preview-before.jpg", after: "/agents/preview-cutout.jpg" },
  "background-replace": { before: "/agents/preview-before.jpg", after: "/agents/preview-after.jpg" },
  "gta-filter": { before: "/agents/gta-filter-before.jpg", after: "/agents/gta-filter-after.jpg" },
  "pro-headshot": { before: "/agents/pro-headshot-before.jpg", after: "/agents/pro-headshot-after.jpg" },
  "face-swap": { before: "/agents/face-swap-2.jpg", after: "/agents/face-swap-after.jpg" },
  "privacy-redaction": { before: "/agents/privacy-redaction-before.jpg", after: "/agents/privacy-redaction-after.jpg" },
  "business-outfit": { before: "/agents/business-outfit-before.jpg", after: "/agents/business-outfit-after.jpg" },
  "natural-retouch": { before: "/agents/natural-retouch-before.jpg", after: "/agents/natural-retouch-after.jpg" },
  "restore-old-photo": { before: "/agents/restore-old-photo-before.jpg", after: "/agents/restore-old-photo-after.jpg" },
  "remove-objects": { before: "/agents/remove-objects-before.jpg", after: "/agents/remove-objects-after.jpg" },
  "apply-tan": { before: "/agents/apply-tan-before.jpg", after: "/agents/apply-tan-after.jpg" },
  "remove-tattoo": { before: "/agents/remove-tattoo-before.jpg", after: "/agents/remove-tattoo-after.jpg" },
  "remove-makeup": { before: "/agents/remove-makeup-before.jpg", after: "/agents/remove-makeup-after.jpg" },
  "add-makeup": { before: "/agents/add-makeup-before.jpg", after: "/agents/add-makeup-after.jpg" },
  "change-eye-color": { before: "/agents/change-eye-color-before.jpg", after: "/agents/change-eye-color-after.jpg" },
  "plump-lips": { before: "/agents/plump-lips-before.jpg", after: "/agents/plump-lips-after.jpg" },
  "whiten-teeth": { before: "/agents/whiten-teeth-before.jpg", after: "/agents/whiten-teeth-after.jpg" },
  "remove-wrinkles": { before: "/agents/remove-wrinkles-before.jpg", after: "/agents/remove-wrinkles-after.jpg" },
  "add-cheekbones": { before: "/agents/add-cheekbones-before.jpg", after: "/agents/add-cheekbones-after.jpg" },
  "character-card": { before: "/agents/character-card-before.jpg", after: "/agents/character-card-after.jpg" },
  kare: { before: "/agents/kare-before.jpg", after: "/agents/kare-after.jpg" },
  bob: { before: "/agents/bob-before.jpg", after: "/agents/bob-after.jpg" },
  cascade: { before: "/agents/cascade-before.jpg", after: "/agents/cascade-after.jpg" },
  "long-bob": { before: "/agents/long-bob-before.jpg", after: "/agents/long-bob-after.jpg" },
  pixie: { before: "/agents/pixie-before.jpg", after: "/agents/pixie-after.jpg" },
  shag: { before: "/agents/shag-before.jpg", after: "/agents/shag-after.jpg" },
  undercut: { before: "/agents/undercut-before.jpg", after: "/agents/undercut-after.jpg" },
  fade: { before: "/agents/fade-before.jpg", after: "/agents/fade-after.jpg" },
  crop: { before: "/agents/crop-before.jpg", after: "/agents/crop-after.jpg" },
  quiff: { before: "/agents/quiff-before.jpg", after: "/agents/quiff-after.jpg" },
  pompadour: { before: "/agents/pompadour-before.jpg", after: "/agents/pompadour-after.jpg" },
  caesar: { before: "/agents/caesar-before.jpg", after: "/agents/caesar-after.jpg" },
  stubble: { before: "/agents/stubble-before.jpg", after: "/agents/stubble-after.jpg" },
  "short-boxed-beard": { before: "/agents/short-boxed-beard-before.jpg", after: "/agents/short-boxed-beard-after.jpg" },
  "full-beard": { before: "/agents/full-beard-before.jpg", after: "/agents/full-beard-after.jpg" },
  goatee: { before: "/agents/goatee-before.jpg", after: "/agents/goatee-after.jpg" },
  "van-dyke": { before: "/agents/van-dyke-before.jpg", after: "/agents/van-dyke-after.jpg" },
  ducktail: { before: "/agents/ducktail-before.jpg", after: "/agents/ducktail-after.jpg" },
  bald: { before: "/agents/bald-before.jpg", after: "/agents/bald-after.jpg" },
  "remove-beard": { before: "/agents/remove-beard-before.jpg", after: "/agents/remove-beard-after.jpg" },
  rain: { before: "/agents/rain-before.jpg", after: "/agents/rain-after.jpg" },
  snow: { before: "/agents/snow-before.jpg", after: "/agents/snow-after.jpg" },
  fog: { before: "/agents/fog-before.jpg", after: "/agents/fog-after.jpg" },
  thunderstorm: { before: "/agents/thunderstorm-before.jpg", after: "/agents/thunderstorm-after.jpg" },
  "sun-rays": { before: "/agents/sun-rays-before.jpg", after: "/agents/sun-rays-after.jpg" },
  overcast: { before: "/agents/overcast-before.jpg", after: "/agents/overcast-after.jpg" },
  sunset: { before: "/agents/sunset-before.jpg", after: "/agents/sunset-after.jpg" },
  "business-suit-man": { before: "/agents/business-suit-man-before.jpg", after: "/agents/business-suit-man-after.jpg" },
  "business-suit-woman": { before: "/agents/business-suit-woman-before.jpg", after: "/agents/business-suit-woman-after.jpg" },
  "military-uniform": { before: "/agents/military-uniform-before.jpg", after: "/agents/military-uniform-after.jpg" },
  "police-uniform": { before: "/agents/police-uniform-before.jpg", after: "/agents/police-uniform-after.jpg" },
  "medical-uniform": { before: "/agents/medical-uniform-before.jpg", after: "/agents/medical-uniform-after.jpg" },
  "firefighter-uniform": { before: "/agents/firefighter-uniform-before.jpg", after: "/agents/firefighter-uniform-after.jpg" },
  "school-uniform": { before: "/agents/school-uniform-before.jpg", after: "/agents/school-uniform-after.jpg" },
  "pilot-uniform": { before: "/agents/pilot-uniform-before.jpg", after: "/agents/pilot-uniform-after.jpg" },
  "flight-attendant": { before: "/agents/flight-attendant-before.jpg", after: "/agents/flight-attendant-after.jpg" },
  cowboy: { before: "/agents/cowboy-before.jpg", after: "/agents/cowboy-after.jpg" },
  "spider-man": { before: "/agents/spider-man-before.jpg", after: "/agents/spider-man-after.jpg" },
  "iron-man": { before: "/agents/iron-man-before.jpg", after: "/agents/iron-man-after.jpg" },
  "captain-america": { before: "/agents/captain-america-before.jpg", after: "/agents/captain-america-after.jpg" },
  thor: { before: "/agents/thor-before.jpg", after: "/agents/thor-after.jpg" },
  "black-widow": { before: "/agents/black-widow-before.jpg", after: "/agents/black-widow-after.jpg" },
  pirate: { before: "/agents/pirate-before.jpg", after: "/agents/pirate-after.jpg" },
  "medieval-knight": { before: "/agents/medieval-knight-before.jpg", after: "/agents/medieval-knight-after.jpg" },
  samurai: { before: "/agents/samurai-before.jpg", after: "/agents/samurai-after.jpg" },
  pharaoh: { before: "/agents/pharaoh-before.jpg", after: "/agents/pharaoh-after.jpg" },
  "venetian-carnival": { before: "/agents/venetian-carnival-before.jpg", after: "/agents/venetian-carnival-after.jpg" },
  "fantasy-mage": { before: "/agents/fantasy-mage-before.jpg", after: "/agents/fantasy-mage-after.jpg" },
  vampire: { before: "/agents/vampire-before.jpg", after: "/agents/vampire-after.jpg" },
  steampunk: { before: "/agents/steampunk-before.jpg", after: "/agents/steampunk-after.jpg" },
  astronaut: { before: "/agents/astronaut-before.jpg", after: "/agents/astronaut-after.jpg" },
  gladiator: { before: "/agents/gladiator-before.jpg", after: "/agents/gladiator-after.jpg" },
  "roman-legionary": { before: "/agents/roman-legionary-before.jpg", after: "/agents/roman-legionary-after.jpg" },
  elf: { before: "/agents/elf-before.jpg", after: "/agents/elf-after.jpg" },
  king: { before: "/agents/king-before.jpg", after: "/agents/king-after.jpg" },
  queen: { before: "/agents/queen-before.jpg", after: "/agents/queen-after.jpg" },
  "rock-star": { before: "/agents/rock-star-before.jpg", after: "/agents/rock-star-after.jpg" },
  santorini: { before: "/agents/santorini-before.jpg", after: "/agents/santorini-after.jpg" },
  cappadocia: { before: "/agents/cappadocia-before.jpg", after: "/agents/cappadocia-after.jpg" },
  dubai: { before: "/agents/dubai-before.jpg", after: "/agents/dubai-after.jpg" },
  paris: { before: "/agents/paris-before.jpg", after: "/agents/paris-after.jpg" },
  maldives: { before: "/agents/maldives-before.jpg", after: "/agents/maldives-after.jpg" },
  iceland: { before: "/agents/iceland-before.jpg", after: "/agents/iceland-after.jpg" },
  dolomites: { before: "/agents/dolomites-before.jpg", after: "/agents/dolomites-after.jpg" },
  kyoto: { before: "/agents/kyoto-before.jpg", after: "/agents/kyoto-after.jpg" },
  petra: { before: "/agents/petra-before.jpg", after: "/agents/petra-after.jpg" },
  "new-york": { before: "/agents/new-york-before.jpg", after: "/agents/new-york-after.jpg" },
  "bora-bora": { before: "/agents/bora-bora-before.jpg", after: "/agents/bora-bora-after.jpg" },
  uyuni: { before: "/agents/uyuni-before.jpg", after: "/agents/uyuni-after.jpg" },
  "cartoon-hero": { before: "/agents/cartoon-hero-before.jpg", after: "/agents/cartoon-hero-after.jpg" },
  caricature: { before: "/agents/caricature-before.jpg", after: "/agents/caricature-after.jpg" },
  "hero-3d": { before: "/agents/hero-3d-before.jpg", after: "/agents/hero-3d-after.jpg" },
  drawn: { before: "/agents/drawn-before.jpg", after: "/agents/drawn-after.jpg" },
  comic: { before: "/agents/comic-before.jpg", after: "/agents/comic-after.jpg" },
  clay: { before: "/agents/clay-before.jpg", after: "/agents/clay-after.jpg" },
  "anime-hero": { before: "/agents/anime-hero-before.jpg", after: "/agents/anime-hero-after.jpg" },
  fantasy: { before: "/agents/fantasy-before.jpg", after: "/agents/fantasy-after.jpg" },
  "pixel-illustration": { before: "/agents/pixel-illustration-before.jpg", after: "/agents/pixel-illustration-after.jpg" },
  watercolor: { before: "/agents/watercolor-before.jpg", after: "/agents/watercolor-after.jpg" },
  "x-ray": { before: "/agents/x-ray-before.jpg", after: "/agents/x-ray-after.jpg" },
  "old-age": { before: "/agents/old-age-before.jpg", after: "/agents/old-age-after.jpg" },
  "fashion-caricature": { before: "/agents/fashion-caricature-before.jpg", after: "/agents/fashion-caricature-after.jpg" },
  "comic-2": { before: "/agents/comic-2-before.jpg", after: "/agents/comic-2-after.jpg" },
  ...Object.fromEntries(IMAGE_AGENT_EXPANSION_IDS.map((id) => [id, { before: `/agents/${id}-before.jpg`, after: `/agents/${id}-after.jpg` }])),
};

export type AgentPreviewKind = "compare" | "photo" | "text";

export const MY_AGENT_COVER = "/agents/my-agent.png";

export function agentPreviewKind(id: string): AgentPreviewKind {
  if (COMPARE_AGENT_IDS.has(id)) return "compare";
  if (id in STILL_COVERS) return "photo";
  return "text";
}

export function isCompareAgentPreview(id: string): boolean {
  return agentPreviewKind(id) === "compare";
}

export function comparePreviewAssets(id: string): { before: string; after: string } {
  return COMPARE_COVERS[id] ?? { before: "/agents/preview-before.jpg", after: "/agents/preview-after.jpg" };
}

export function stillPreviewSrc(id: string): string {
  return STILL_COVERS[id] ?? "/agents/preview-before.jpg";
}

/** Карточки на главной и в галерее: лёгкий webp, не исходный JPG на 2–3 МБ. */
function agentCardThumb(src: string): string {
  const file = src.split("/").pop() ?? "preview-before.jpg";
  const stem = file.replace(/\.[^.]+$/, "");
  return `/agents/thumbs/${stem}.webp`;
}

export function cardComparePreviewAssets(id: string): { before: string; after: string } {
  const full = comparePreviewAssets(id);
  return { before: agentCardThumb(full.before), after: agentCardThumb(full.after) };
}

export function cardStillPreviewSrc(id: string): string {
  return agentCardThumb(stillPreviewSrc(id));
}

const COMPARE_LABELS: Record<string, { before: string; after: string }> = {
  ru: { before: "До", after: "После" },
  en: { before: "Before", after: "After" },
  de: { before: "Vorher", after: "Nachher" },
  es: { before: "Antes", after: "Después" },
  fr: { before: "Avant", after: "Après" },
  it: { before: "Prima", after: "Dopo" },
  pt: { before: "Antes", after: "Depois" },
  pl: { before: "Przed", after: "Po" },
  tr: { before: "Önce", after: "Sonra" },
  cs: { before: "Před", after: "Po" },
  sv: { before: "Före", after: "Efter" },
  hi: { before: "पहले", after: "बाद" },
  ar: { before: "قبل", after: "بعد" },
};

export function compareCornerLabels(locale: string): { before: string; after: string } {
  return COMPARE_LABELS[locale] ?? COMPARE_LABELS.en;
}
