import type { Locale } from "./i18n/types";

export type AuthActionCopy = {
  subject: string;
  preheader: string;
  kicker: string;
  title: string;
  body: string;
  button: string;
  fallback: string;
  footer: string;
  text: (url: string) => string;
};

export type AuthMailCopy = {
  verification: AuthActionCopy;
  reset: AuthActionCopy;
};

const LOCALES: Locale[] = [
  "en", "zh", "hi", "es", "fr", "ar", "pt", "ru", "de", "ja", "it", "ko", "tr", "pl", "nl", "sv", "cs", "el", "ro",
];

const copies: Record<Locale, AuthMailCopy> = {
  en: {
    verification: {
      subject: "Confirm your Genora.art registration",
      preheader: "One click to finish registration and open the models.",
      kicker: "Registration",
      title: "Confirm your email",
      body: "Click the button below to finish creating your Genora.art account and get access to the models.",
      button: "Confirm registration",
      fallback: "If the button does not work, copy this link into your browser:",
      footer: "This link is valid for 24 hours. If you did not create an account, you can ignore this email. Genora.art · support@genora.art",
      text: (url) => `Confirm your email to finish Genora.art registration:\n${url}\n\nThis link is valid for 24 hours. If you did not register, ignore this email.`,
    },
    reset: {
      subject: "Reset your Genora.art password",
      preheader: "Create a new password. This link is valid for 1 hour.",
      kicker: "Password",
      title: "Set a new password",
      body: "We received a request to restore access to your Genora.art account. Click the button below to choose a new password.",
      button: "Change password",
      fallback: "If the button does not work, copy this link into your browser:",
      footer: "This link is valid for 1 hour and can be used once. If you did not ask to reset the password, ignore this email. Genora.art · support@genora.art",
      text: (url) => `Set a new Genora.art password:\n${url}\n\nThis link is valid for 1 hour. If you did not request a reset, ignore this email.`,
    },
  },
  ru: {
    verification: {
      subject: "Подтвердите регистрацию в Genora.art",
      preheader: "Одно нажатие — и регистрация завершена.",
      kicker: "Регистрация",
      title: "Подтвердите ваш email",
      body: "Нажмите кнопку ниже, чтобы завершить регистрацию в Genora.art и получить доступ к моделям.",
      button: "Подтвердить регистрацию",
      fallback: "Если кнопка не открывается, скопируйте ссылку в браузер:",
      footer: "Ссылка действует 24 часа. Если вы не создавали аккаунт, просто проигнорируйте письмо. Genora.art · support@genora.art",
      text: (url) => `Подтвердите email, чтобы завершить регистрацию в Genora.art:\n${url}\n\nСсылка действует 24 часа. Если вы не регистрировались, проигнорируйте письмо.`,
    },
    reset: {
      subject: "Восстановление пароля Genora.art",
      preheader: "Задайте новый пароль. Ссылка действует 1 час.",
      kicker: "Пароль",
      title: "Задайте новый пароль",
      body: "Мы получили запрос на восстановление доступа к вашему аккаунту Genora.art. Нажмите кнопку, чтобы задать новый пароль.",
      button: "Сменить пароль",
      fallback: "Если кнопка не открывается, скопируйте ссылку в браузер:",
      footer: "Ссылка действует 1 час и может быть использована один раз. Если вы не запрашивали сброс, проигнорируйте письмо. Genora.art · support@genora.art",
      text: (url) => `Задайте новый пароль Genora.art:\n${url}\n\nСсылка действует 1 час. Если вы не запрашивали сброс, проигнорируйте письмо.`,
    },
  },
  zh: {
    verification: {
      subject: "确认您的 Genora.art 注册",
      preheader: "点击一次即可完成注册并使用模型。",
      kicker: "注册",
      title: "确认您的邮箱",
      body: "点击下方按钮完成 Genora.art 注册并获得模型访问权限。",
      button: "确认注册",
      fallback: "如果按钮无法打开，请将此链接复制到浏览器：",
      footer: "链接 24 小时内有效。如果您没有注册，请忽略此邮件。Genora.art · support@genora.art",
      text: (url) => `请确认邮箱以完成 Genora.art 注册：\n${url}\n\n链接 24 小时内有效。如非本人注册，请忽略此邮件。`,
    },
    reset: {
      subject: "重置您的 Genora.art 密码",
      preheader: "设置新密码。链接 1 小时内有效。",
      kicker: "密码",
      title: "设置新密码",
      body: "我们收到了恢复您 Genora.art 账户的请求。点击下方按钮设置新密码。",
      button: "更改密码",
      fallback: "如果按钮无法打开，请将此链接复制到浏览器：",
      footer: "链接 1 小时内有效，且只能使用一次。如果您没有申请重置，请忽略此邮件。Genora.art · support@genora.art",
      text: (url) => `设置新的 Genora.art 密码：\n${url}\n\n链接 1 小时内有效。如非本人申请，请忽略此邮件。`,
    },
  },
  hi: {
    verification: {
      subject: "Genora.art पंजीकरण की पुष्टि करें",
      preheader: "एक क्लिक में पंजीकरण पूरा करें और मॉडल खोलें।",
      kicker: "पंजीकरण",
      title: "अपना ईमेल पुष्टि करें",
      body: "Genora.art खाता पूरा करने और मॉडल तक पहुँच पाने के लिए नीचे दिए बटन पर क्लिक करें।",
      button: "पंजीकरण पुष्टि करें",
      fallback: "यदि बटन नहीं खुलता, तो यह लिंक ब्राउज़र में कॉपी करें:",
      footer: "यह लिंक 24 घंटे तक मान्य है। यदि आपने खाता नहीं बनाया, तो इस ईमेल को अनदेखा करें। Genora.art · support@genora.art",
      text: (url) => `Genora.art पंजीकरण पूरा करने के लिए ईमेल की पुष्टि करें:\n${url}\n\nलिंक 24 घंटे तक मान्य है।`,
    },
    reset: {
      subject: "अपना Genora.art पासवर्ड रीसेट करें",
      preheader: "नया पासवर्ड सेट करें। लिंक 1 घंटे तक मान्य है।",
      kicker: "पासवर्ड",
      title: "नया पासवर्ड सेट करें",
      body: "हमें आपके Genora.art खाते की पहुँच बहाल करने का अनुरोध मिला है। नया पासवर्ड चुनने के लिए बटन दबाएँ।",
      button: "पासवर्ड बदलें",
      fallback: "यदि बटन नहीं खुलता, तो यह लिंक ब्राउज़र में कॉपी करें:",
      footer: "यह लिंक 1 घंटे तक मान्य है और एक बार ही उपयोग किया जा सकता है। यदि आपने रीसेट नहीं मांगा, तो ईमेल अनदेखा करें। Genora.art · support@genora.art",
      text: (url) => `नया Genora.art पासवर्ड सेट करें:\n${url}\n\nलिंक 1 घंटे तक मान्य है।`,
    },
  },
  es: {
    verification: {
      subject: "Confirma tu registro en Genora.art",
      preheader: "Un clic para terminar el registro y abrir los modelos.",
      kicker: "Registro",
      title: "Confirma tu correo",
      body: "Pulsa el botón para terminar de crear tu cuenta de Genora.art y acceder a los modelos.",
      button: "Confirmar registro",
      fallback: "Si el botón no funciona, copia este enlace en el navegador:",
      footer: "El enlace es válido 24 horas. Si no creaste una cuenta, ignora este correo. Genora.art · support@genora.art",
      text: (url) => `Confirma tu correo para terminar el registro en Genora.art:\n${url}\n\nEl enlace es válido 24 horas.`,
    },
    reset: {
      subject: "Restablece tu contraseña de Genora.art",
      preheader: "Crea una nueva contraseña. El enlace vale 1 hora.",
      kicker: "Contraseña",
      title: "Elige una nueva contraseña",
      body: "Hemos recibido una solicitud para restaurar el acceso a tu cuenta de Genora.art. Pulsa el botón para elegir una nueva contraseña.",
      button: "Cambiar contraseña",
      fallback: "Si el botón no funciona, copia este enlace en el navegador:",
      footer: "El enlace es válido 1 hora y solo se puede usar una vez. Si no pediste el restablecimiento, ignora este correo. Genora.art · support@genora.art",
      text: (url) => `Elige una nueva contraseña de Genora.art:\n${url}\n\nEl enlace es válido 1 hora.`,
    },
  },
  fr: {
    verification: {
      subject: "Confirmez votre inscription à Genora.art",
      preheader: "Un clic pour terminer l’inscription et ouvrir les modèles.",
      kicker: "Inscription",
      title: "Confirmez votre e-mail",
      body: "Cliquez sur le bouton pour terminer la création de votre compte Genora.art et accéder aux modèles.",
      button: "Confirmer l’inscription",
      fallback: "Si le bouton ne s’ouvre pas, copiez ce lien dans votre navigateur :",
      footer: "Le lien est valable 24 heures. Si vous n’avez pas créé de compte, ignorez cet e-mail. Genora.art · support@genora.art",
      text: (url) => `Confirmez votre e-mail pour terminer l’inscription à Genora.art :\n${url}\n\nLe lien est valable 24 heures.`,
    },
    reset: {
      subject: "Réinitialisez votre mot de passe Genora.art",
      preheader: "Choisissez un nouveau mot de passe. Le lien est valable 1 heure.",
      kicker: "Mot de passe",
      title: "Définir un nouveau mot de passe",
      body: "Nous avons reçu une demande de restauration d’accès à votre compte Genora.art. Cliquez sur le bouton pour choisir un nouveau mot de passe.",
      button: "Changer le mot de passe",
      fallback: "Si le bouton ne s’ouvre pas, copiez ce lien dans votre navigateur :",
      footer: "Le lien est valable 1 heure et ne peut être utilisé qu’une fois. Si vous n’avez pas demandé cette réinitialisation, ignorez cet e-mail. Genora.art · support@genora.art",
      text: (url) => `Définissez un nouveau mot de passe Genora.art :\n${url}\n\nLe lien est valable 1 heure.`,
    },
  },
  ar: {
    verification: {
      subject: "أكد تسجيلك في Genora.art",
      preheader: "نقرة واحدة لإكمال التسجيل وفتح النماذج.",
      kicker: "التسجيل",
      title: "أكد بريدك الإلكتروني",
      body: "اضغط الزر أدناه لإكمال إنشاء حساب Genora.art والوصول إلى النماذج.",
      button: "تأكيد التسجيل",
      fallback: "إذا لم يعمل الزر، انسخ هذا الرابط إلى المتصفح:",
      footer: "الرابط صالح لمدة 24 ساعة. إذا لم تنشئ حسابًا، تجاهل هذه الرسالة. Genora.art · support@genora.art",
      text: (url) => `أكد بريدك لإكمال التسجيل في Genora.art:\n${url}\n\nالرابط صالح لمدة 24 ساعة.`,
    },
    reset: {
      subject: "إعادة تعيين كلمة مرور Genora.art",
      preheader: "عيّن كلمة مرور جديدة. الرابط صالح لمدة ساعة.",
      kicker: "كلمة المرور",
      title: "تعيين كلمة مرور جديدة",
      body: "تلقينا طلبًا لاستعادة الوصول إلى حسابك في Genora.art. اضغط الزر لاختيار كلمة مرور جديدة.",
      button: "تغيير كلمة المرور",
      fallback: "إذا لم يعمل الزر، انسخ هذا الرابط إلى المتصفح:",
      footer: "الرابط صالح لمدة ساعة ويمكن استخدامه مرة واحدة. إذا لم تطلب إعادة التعيين، تجاهل هذه الرسالة. Genora.art · support@genora.art",
      text: (url) => `عيّن كلمة مرور جديدة لـ Genora.art:\n${url}\n\nالرابط صالح لمدة ساعة.`,
    },
  },
  pt: {
    verification: {
      subject: "Confirme o seu cadastro no Genora.art",
      preheader: "Um clique para concluir o cadastro e abrir os modelos.",
      kicker: "Cadastro",
      title: "Confirme o seu e-mail",
      body: "Clique no botão abaixo para concluir a criação da sua conta Genora.art e acessar os modelos.",
      button: "Confirmar cadastro",
      fallback: "Se o botão não abrir, copie este link no navegador:",
      footer: "O link vale por 24 horas. Se você não criou uma conta, ignore este e-mail. Genora.art · support@genora.art",
      text: (url) => `Confirme o e-mail para concluir o cadastro no Genora.art:\n${url}\n\nO link vale por 24 horas.`,
    },
    reset: {
      subject: "Redefina a sua senha do Genora.art",
      preheader: "Crie uma nova senha. O link vale por 1 hora.",
      kicker: "Senha",
      title: "Defina uma nova senha",
      body: "Recebemos um pedido para restaurar o acesso à sua conta Genora.art. Clique no botão para escolher uma nova senha.",
      button: "Alterar senha",
      fallback: "Se o botão não abrir, copie este link no navegador:",
      footer: "O link vale por 1 hora e só pode ser usado uma vez. Se você não pediu a redefinição, ignore este e-mail. Genora.art · support@genora.art",
      text: (url) => `Defina uma nova senha do Genora.art:\n${url}\n\nO link vale por 1 hora.`,
    },
  },
  de: {
    verification: {
      subject: "Bestätigen Sie Ihre Genora.art-Registrierung",
      preheader: "Ein Klick, um die Registrierung abzuschließen.",
      kicker: "Registrierung",
      title: "Bestätigen Sie Ihre E-Mail",
      body: "Klicken Sie auf die Schaltfläche, um Ihr Genora.art-Konto zu vollenden und Modelle zu nutzen.",
      button: "Registrierung bestätigen",
      fallback: "Wenn die Schaltfläche nicht funktioniert, kopieren Sie diesen Link in den Browser:",
      footer: "Der Link gilt 24 Stunden. Wenn Sie kein Konto erstellt haben, ignorieren Sie diese E-Mail. Genora.art · support@genora.art",
      text: (url) => `Bestätigen Sie Ihre E-Mail, um die Genora.art-Registrierung abzuschließen:\n${url}\n\nDer Link gilt 24 Stunden.`,
    },
    reset: {
      subject: "Genora.art-Passwort zurücksetzen",
      preheader: "Legen Sie ein neues Passwort fest. Der Link gilt 1 Stunde.",
      kicker: "Passwort",
      title: "Neues Passwort festlegen",
      body: "Wir haben eine Anfrage erhalten, den Zugang zu Ihrem Genora.art-Konto wiederherzustellen. Klicken Sie auf die Schaltfläche, um ein neues Passwort zu wählen.",
      button: "Passwort ändern",
      fallback: "Wenn die Schaltfläche nicht funktioniert, kopieren Sie diesen Link in den Browser:",
      footer: "Der Link gilt 1 Stunde und kann nur einmal verwendet werden. Wenn Sie keine Zurücksetzung angefordert haben, ignorieren Sie diese E-Mail. Genora.art · support@genora.art",
      text: (url) => `Legen Sie ein neues Genora.art-Passwort fest:\n${url}\n\nDer Link gilt 1 Stunde.`,
    },
  },
  ja: {
    verification: {
      subject: "Genora.artの登録を確認してください",
      preheader: "ワンクリックで登録を完了し、モデルを利用できます。",
      kicker: "登録",
      title: "メールアドレスを確認",
      body: "下のボタンを押して Genora.art アカウントの作成を完了し、モデルをご利用ください。",
      button: "登録を確認",
      fallback: "ボタンが開かない場合は、このリンクをブラウザにコピーしてください:",
      footer: "リンクの有効期限は24時間です。アカウントを作成していない場合は、このメールを無視してください。Genora.art · support@genora.art",
      text: (url) => `Genora.artの登録を完了するにはメールを確認してください:\n${url}\n\nリンクの有効期限は24時間です。`,
    },
    reset: {
      subject: "Genora.artのパスワードを再設定",
      preheader: "新しいパスワードを設定します。リンクの有効期限は1時間です。",
      kicker: "パスワード",
      title: "新しいパスワードを設定",
      body: "Genora.art アカウントへのアクセス復旧リクエストを受け取りました。ボタンを押して新しいパスワードを設定してください。",
      button: "パスワードを変更",
      fallback: "ボタンが開かない場合は、このリンクをブラウザにコピーしてください:",
      footer: "リンクの有効期限は1時間で、1回のみ使用できます。再設定を依頼していない場合は、このメールを無視してください。Genora.art · support@genora.art",
      text: (url) => `新しい Genora.art パスワードを設定してください:\n${url}\n\nリンクの有効期限は1時間です。`,
    },
  },
  it: {
    verification: {
      subject: "Conferma la registrazione a Genora.art",
      preheader: "Un clic per completare la registrazione e aprire i modelli.",
      kicker: "Registrazione",
      title: "Conferma la tua email",
      body: "Clicca il pulsante per completare la creazione del tuo account Genora.art e accedere ai modelli.",
      button: "Conferma registrazione",
      fallback: "Se il pulsante non si apre, copia questo link nel browser:",
      footer: "Il link è valido 24 ore. Se non hai creato un account, ignora questa email. Genora.art · support@genora.art",
      text: (url) => `Conferma l’email per completare la registrazione a Genora.art:\n${url}\n\nIl link è valido 24 ore.`,
    },
    reset: {
      subject: "Reimposta la password di Genora.art",
      preheader: "Scegli una nuova password. Il link è valido 1 ora.",
      kicker: "Password",
      title: "Imposta una nuova password",
      body: "Abbiamo ricevuto una richiesta per ripristinare l’accesso al tuo account Genora.art. Clicca il pulsante per scegliere una nuova password.",
      button: "Cambia password",
      fallback: "Se il pulsante non si apre, copia questo link nel browser:",
      footer: "Il link è valido 1 ora e può essere usato una sola volta. Se non hai chiesto la reimpostazione, ignora questa email. Genora.art · support@genora.art",
      text: (url) => `Imposta una nuova password Genora.art:\n${url}\n\nIl link è valido 1 ora.`,
    },
  },
  ko: {
    verification: {
      subject: "Genora.art 가입을 확인해 주세요",
      preheader: "한 번만 클릭하면 가입이 완료되고 모델을 사용할 수 있습니다.",
      kicker: "가입",
      title: "이메일을 확인하세요",
      body: "아래 버튼을 눌러 Genora.art 계정 생성을 완료하고 모델을 이용하세요.",
      button: "가입 확인",
      fallback: "버튼이 열리지 않으면 이 링크를 브라우저에 복사하세요:",
      footer: "링크는 24시간 동안 유효합니다. 계정을 만들지 않으셨다면 이 메일을 무시하세요. Genora.art · support@genora.art",
      text: (url) => `Genora.art 가입을 완료하려면 이메일을 확인하세요:\n${url}\n\n링크는 24시간 동안 유효합니다.`,
    },
    reset: {
      subject: "Genora.art 비밀번호 재설정",
      preheader: "새 비밀번호를 설정하세요. 링크는 1시간 동안 유효합니다.",
      kicker: "비밀번호",
      title: "새 비밀번호 설정",
      body: "Genora.art 계정 접근 복구 요청을 받았습니다. 아래 버튼을 눌러 새 비밀번호를 선택하세요.",
      button: "비밀번호 변경",
      fallback: "버튼이 열리지 않으면 이 링크를 브라우저에 복사하세요:",
      footer: "링크는 1시간 동안 유효하며 한 번만 사용할 수 있습니다. 재설정을 요청하지 않으셨다면 이 메일을 무시하세요. Genora.art · support@genora.art",
      text: (url) => `새 Genora.art 비밀번호를 설정하세요:\n${url}\n\n링크는 1시간 동안 유효합니다.`,
    },
  },
  tr: {
    verification: {
      subject: "Genora.art kaydınızı doğrulayın",
      preheader: "Kaydı tamamlamak ve modellere ulaşmak için bir tıklama.",
      kicker: "Kayıt",
      title: "E-postanızı doğrulayın",
      body: "Genora.art hesabınızı tamamlamak ve modellere erişmek için aşağıdaki düğmeye tıklayın.",
      button: "Kaydı doğrula",
      fallback: "Düğme açılmazsa bu bağlantıyı tarayıcıya kopyalayın:",
      footer: "Bağlantı 24 saat geçerlidir. Hesap oluşturmadıysanız bu e-postayı yok sayın. Genora.art · support@genora.art",
      text: (url) => `Genora.art kaydını tamamlamak için e-postanızı doğrulayın:\n${url}\n\nBağlantı 24 saat geçerlidir.`,
    },
    reset: {
      subject: "Genora.art parolanızı sıfırlayın",
      preheader: "Yeni bir parola belirleyin. Bağlantı 1 saat geçerlidir.",
      kicker: "Parola",
      title: "Yeni parola belirleyin",
      body: "Genora.art hesabınıza erişimi geri yükleme isteği aldık. Yeni bir parola seçmek için düğmeye tıklayın.",
      button: "Parolayı değiştir",
      fallback: "Düğme açılmazsa bu bağlantıyı tarayıcıya kopyalayın:",
      footer: "Bağlantı 1 saat geçerlidir ve yalnızca bir kez kullanılabilir. Sıfırlama istemediyseniz bu e-postayı yok sayın. Genora.art · support@genora.art",
      text: (url) => `Yeni bir Genora.art parolası belirleyin:\n${url}\n\nBağlantı 1 saat geçerlidir.`,
    },
  },
  pl: {
    verification: {
      subject: "Potwierdź rejestrację w Genora.art",
      preheader: "Jedno kliknięcie kończy rejestrację i otwiera modele.",
      kicker: "Rejestracja",
      title: "Potwierdź swój e-mail",
      body: "Kliknij przycisk, aby dokończyć tworzenie konta Genora.art i uzyskać dostęp do modeli.",
      button: "Potwierdź rejestrację",
      fallback: "Jeśli przycisk nie działa, skopiuj ten link do przeglądarki:",
      footer: "Link jest ważny 24 godziny. Jeśli nie zakładałeś konta, zignoruj tę wiadomość. Genora.art · support@genora.art",
      text: (url) => `Potwierdź e-mail, aby dokończyć rejestrację w Genora.art:\n${url}\n\nLink jest ważny 24 godziny.`,
    },
    reset: {
      subject: "Zresetuj hasło Genora.art",
      preheader: "Ustaw nowe hasło. Link jest ważny 1 godzinę.",
      kicker: "Hasło",
      title: "Ustaw nowe hasło",
      body: "Otrzymaliśmy prośbę o przywrócenie dostępu do Twojego konta Genora.art. Kliknij przycisk, aby wybrać nowe hasło.",
      button: "Zmień hasło",
      fallback: "Jeśli przycisk nie działa, skopiuj ten link do przeglądarki:",
      footer: "Link jest ważny 1 godzinę i można go użyć tylko raz. Jeśli nie prosiłeś o reset, zignoruj tę wiadomość. Genora.art · support@genora.art",
      text: (url) => `Ustaw nowe hasło Genora.art:\n${url}\n\nLink jest ważny 1 godzinę.`,
    },
  },
  nl: {
    verification: {
      subject: "Bevestig je Genora.art-registratie",
      preheader: "Eén klik om de registratie af te ronden en de modellen te openen.",
      kicker: "Registratie",
      title: "Bevestig je e-mail",
      body: "Klik op de knop om je Genora.art-account af te ronden en toegang tot de modellen te krijgen.",
      button: "Registratie bevestigen",
      fallback: "Als de knop niet werkt, kopieer deze link naar je browser:",
      footer: "De link is 24 uur geldig. Als je geen account hebt gemaakt, kun je deze e-mail negeren. Genora.art · support@genora.art",
      text: (url) => `Bevestig je e-mail om de Genora.art-registratie af te ronden:\n${url}\n\nDe link is 24 uur geldig.`,
    },
    reset: {
      subject: "Reset je Genora.art-wachtwoord",
      preheader: "Kies een nieuw wachtwoord. De link is 1 uur geldig.",
      kicker: "Wachtwoord",
      title: "Stel een nieuw wachtwoord in",
      body: "We hebben een verzoek ontvangen om de toegang tot je Genora.art-account te herstellen. Klik op de knop om een nieuw wachtwoord te kiezen.",
      button: "Wachtwoord wijzigen",
      fallback: "Als de knop niet werkt, kopieer deze link naar je browser:",
      footer: "De link is 1 uur geldig en kan maar één keer worden gebruikt. Als jij geen reset hebt gevraagd, negeer deze e-mail. Genora.art · support@genora.art",
      text: (url) => `Stel een nieuw Genora.art-wachtwoord in:\n${url}\n\nDe link is 1 uur geldig.`,
    },
  },
  sv: {
    verification: {
      subject: "Bekräfta din Genora.art-registrering",
      preheader: "Ett klick för att slutföra registreringen och öppna modellerna.",
      kicker: "Registrering",
      title: "Bekräfta din e-post",
      body: "Klicka på knappen för att slutföra skapandet av ditt Genora.art-konto och få tillgång till modellerna.",
      button: "Bekräfta registrering",
      fallback: "Om knappen inte fungerar, kopiera den här länken till webbläsaren:",
      footer: "Länken gäller i 24 timmar. Om du inte skapade ett konto kan du ignorera mejlet. Genora.art · support@genora.art",
      text: (url) => `Bekräfta din e-post för att slutföra Genora.art-registreringen:\n${url}\n\nLänken gäller i 24 timmar.`,
    },
    reset: {
      subject: "Återställ ditt Genora.art-lösenord",
      preheader: "Välj ett nytt lösenord. Länken gäller i 1 timme.",
      kicker: "Lösenord",
      title: "Ange ett nytt lösenord",
      body: "Vi har fått en begäran om att återställa åtkomsten till ditt Genora.art-konto. Klicka på knappen för att välja ett nytt lösenord.",
      button: "Byt lösenord",
      fallback: "Om knappen inte fungerar, kopiera den här länken till webbläsaren:",
      footer: "Länken gäller i 1 timme och kan användas en gång. Om du inte bad om en återställning, ignorera mejlet. Genora.art · support@genora.art",
      text: (url) => `Ange ett nytt Genora.art-lösenord:\n${url}\n\nLänken gäller i 1 timme.`,
    },
  },
  cs: {
    verification: {
      subject: "Potvrďte registraci v Genora.art",
      preheader: "Jedním kliknutím dokončíte registraci a otevřete modely.",
      kicker: "Registrace",
      title: "Potvrďte e-mail",
      body: "Klikněte na tlačítko a dokončete vytvoření účtu Genora.art, abyste získali přístup k modelům.",
      button: "Potvrdit registraci",
      fallback: "Pokud tlačítko nefunguje, zkopírujte tento odkaz do prohlížeče:",
      footer: "Odkaz platí 24 hodin. Pokud jste účet nevytvořili, e-mail ignorujte. Genora.art · support@genora.art",
      text: (url) => `Potvrďte e-mail a dokončete registraci v Genora.art:\n${url}\n\nOdkaz platí 24 hodin.`,
    },
    reset: {
      subject: "Obnovte heslo k Genora.art",
      preheader: "Nastavte nové heslo. Odkaz platí 1 hodinu.",
      kicker: "Heslo",
      title: "Nastavte nové heslo",
      body: "Obdrželi jsme žádost o obnovení přístupu k vašemu účtu Genora.art. Klikněte na tlačítko a zvolte nové heslo.",
      button: "Změnit heslo",
      fallback: "Pokud tlačítko nefunguje, zkopírujte tento odkaz do prohlížeče:",
      footer: "Odkaz platí 1 hodinu a lze ho použít jen jednou. Pokud jste obnovení nepožadovali, e-mail ignorujte. Genora.art · support@genora.art",
      text: (url) => `Nastavte nové heslo k Genora.art:\n${url}\n\nOdkaz platí 1 hodinu.`,
    },
  },
  el: {
    verification: {
      subject: "Επιβεβαιώστε την εγγραφή σας στο Genora.art",
      preheader: "Ένα κλικ για να ολοκληρώσετε την εγγραφή και να ανοίξετε τα μοντέλα.",
      kicker: "Εγγραφή",
      title: "Επιβεβαιώστε το email σας",
      body: "Πατήστε το κουμπί για να ολοκληρώσετε τη δημιουργία του λογαριασμού Genora.art και να αποκτήσετε πρόσβαση στα μοντέλα.",
      button: "Επιβεβαίωση εγγραφής",
      fallback: "Αν το κουμπί δεν ανοίγει, αντιγράψτε αυτόν τον σύνδεσμο στο πρόγραμμα περιήγησης:",
      footer: "Ο σύνδεσμος ισχύει για 24 ώρες. Αν δεν δημιουργήσατε λογαριασμό, αγνοήστε αυτό το μήνυμα. Genora.art · support@genora.art",
      text: (url) => `Επιβεβαιώστε το email για να ολοκληρώσετε την εγγραφή στο Genora.art:\n${url}\n\nΟ σύνδεσμος ισχύει για 24 ώρες.`,
    },
    reset: {
      subject: "Επαναφορά κωδικού Genora.art",
      preheader: "Ορίστε νέο κωδικό. Ο σύνδεσμος ισχύει για 1 ώρα.",
      kicker: "Κωδικός",
      title: "Ορίστε νέο κωδικό",
      body: "Λάβαμε αίτημα επαναφοράς πρόσβασης στον λογαριασμό σας Genora.art. Πατήστε το κουμπί για να επιλέξετε νέο κωδικό.",
      button: "Αλλαγή κωδικού",
      fallback: "Αν το κουμπί δεν ανοίγει, αντιγράψτε αυτόν τον σύνδεσμο στο πρόγραμμα περιήγησης:",
      footer: "Ο σύνδεσμος ισχύει για 1 ώρα και χρησιμοποιείται μία φορά. Αν δεν ζητήσατε επαναφορά, αγνοήστε αυτό το μήνυμα. Genora.art · support@genora.art",
      text: (url) => `Ορίστε νέο κωδικό Genora.art:\n${url}\n\nΟ σύνδεσμος ισχύει για 1 ώρα.`,
    },
  },
  ro: {
    verification: {
      subject: "Confirmă înregistrarea în Genora.art",
      preheader: "Un clic pentru a finaliza înregistrarea și a deschide modelele.",
      kicker: "Înregistrare",
      title: "Confirmă adresa de e-mail",
      body: "Apasă butonul pentru a finaliza crearea contului Genora.art și a accesa modelele.",
      button: "Confirmă înregistrarea",
      fallback: "Dacă butonul nu se deschide, copiază acest link în browser:",
      footer: "Linkul este valabil 24 de ore. Dacă nu ai creat un cont, ignoră acest e-mail. Genora.art · support@genora.art",
      text: (url) => `Confirmă e-mailul pentru a finaliza înregistrarea în Genora.art:\n${url}\n\nLinkul este valabil 24 de ore.`,
    },
    reset: {
      subject: "Resetează parola Genora.art",
      preheader: "Setează o parolă nouă. Linkul este valabil 1 oră.",
      kicker: "Parolă",
      title: "Setează o parolă nouă",
      body: "Am primit o cerere de restabilire a accesului la contul tău Genora.art. Apasă butonul pentru a alege o parolă nouă.",
      button: "Schimbă parola",
      fallback: "Dacă butonul nu se deschide, copiază acest link în browser:",
      footer: "Linkul este valabil 1 oră și poate fi folosit o singură dată. Dacă nu ai cerut resetarea, ignoră acest e-mail. Genora.art · support@genora.art",
      text: (url) => `Setează o parolă nouă Genora.art:\n${url}\n\nLinkul este valabil 1 oră.`,
    },
  },
};

export function authMailLocales(): Locale[] {
  return LOCALES;
}

export function getAuthMailCopy(locale?: string | null): AuthMailCopy {
  if (locale && locale in copies) return copies[locale as Locale];
  return copies.en;
}
