import type { Locale } from "./i18n/types";

export type MailCopy = {
  verificationSubject: string;
  verificationTitle: string;
  verificationBody: string;
  verificationButton: string;
  verificationFooter: string;
  verificationText: (url: string) => string;
  supportReceiptSubject: (id: string) => string;
  supportReceiptTitle: string;
  supportReceiptDoNotReply: string;
  supportReceiptTopic: string;
  supportReceiptWorking: string;
  supportReceiptText: (id: string, topic: string, message: string) => string;
  supportReplySubject: (id: string) => string;
  supportSignOff: string;
  topics: Record<string, string>;
};

const en: MailCopy = {
  verificationSubject: "Confirm your Genora.art registration",
  verificationTitle: "Confirm your email",
  verificationBody: "Click the button below to finish registration and get access to the models.",
  verificationButton: "Confirm registration",
  verificationFooter: "This link is valid for 24 hours. If you did not create an account, you can ignore this email.",
  verificationText: (url) => `Confirm your email to finish Genora.art registration: ${url}\n\nThis link is valid for 24 hours. If you did not register, ignore this email.`,
  supportReceiptSubject: (id) => `[${id}] We received your request — Genora.art`,
  supportReceiptTitle: "We received your request",
  supportReceiptDoNotReply: "Please do not reply to this email.",
  supportReceiptTopic: "Topic",
  supportReceiptWorking: "We are already looking into your question.",
  supportReceiptText: (id, topic, message) => `${id}. Please do not reply to this email.\n\nWe received a request about “${topic}”.\n\nYour message:\n${message}\n\nWe are already looking into your question.`,
  supportReplySubject: (id) => `[${id}] Genora.art support reply`,
  supportSignOff: "Best regards,\nGenora.art Support",
  topics: { cooperation: "Partnership", "billing-refund": "Billing or refund", other: "Other", "inbound-email": "Email inquiry" },
};

const ru: MailCopy = {
  verificationSubject: "Подтвердите регистрацию в Genora.art",
  verificationTitle: "Подтвердите ваш email",
  verificationBody: "Нажмите кнопку ниже, чтобы завершить регистрацию и получить доступ к моделям.",
  verificationButton: "Подтвердить регистрацию",
  verificationFooter: "Ссылка действует 24 часа. Если вы не создавали аккаунт, ничего делать не нужно.",
  verificationText: (url) => `Подтвердите email, чтобы завершить регистрацию в Genora.art: ${url}\n\nСсылка действует 24 часа. Если вы не регистрировались, просто проигнорируйте письмо.`,
  supportReceiptSubject: (id) => `[${id}] Обращение принято — Genora.art`,
  supportReceiptTitle: "Мы получили ваш запрос",
  supportReceiptDoNotReply: "Не отвечайте на это письмо.",
  supportReceiptTopic: "Тема",
  supportReceiptWorking: "Мы уже занимаемся вашим вопросом.",
  supportReceiptText: (id, topic, message) => `${id}. Не отвечайте на это письмо.\n\nМы получили запрос на тему «${topic}».\n\nВаше сообщение:\n${message}\n\nМы уже занимаемся вашим вопросом.`,
  supportReplySubject: (id) => `[${id}] Ответ службы поддержки Genora.art`,
  supportSignOff: "С уважением,\nСлужба поддержки Genora.art",
  topics: { cooperation: "Сотрудничество", "billing-refund": "Оплата и возврат", other: "Другой вопрос", "inbound-email": "Письмо на почту" },
};

const copies: Partial<Record<Locale, MailCopy>> = {
  en,
  ru,
  zh: {
    ...en,
    verificationSubject: "确认您的 Genora.art 注册",
    verificationTitle: "确认您的邮箱",
    verificationBody: "点击下方按钮完成注册并使用模型。",
    verificationButton: "确认注册",
    verificationFooter: "链接 24 小时内有效。如果您没有注册，请忽略此邮件。",
    verificationText: (url) => `请确认邮箱以完成 Genora.art 注册：${url}\n\n链接 24 小时内有效。如非本人注册，请忽略此邮件。`,
    supportReceiptSubject: (id) => `[${id}] 我们已收到您的请求 — Genora.art`,
    supportReceiptTitle: "我们已收到您的请求",
    supportReceiptDoNotReply: "请不要回复此邮件。",
    supportReceiptTopic: "主题",
    supportReceiptWorking: "我们正在处理您的问题。",
    supportReceiptText: (id, topic, message) => `${id}。请不要回复此邮件。\n\n我们收到了关于「${topic}」的请求。\n\n您的留言：\n${message}\n\n我们正在处理您的问题。`,
    supportReplySubject: (id) => `[${id}] Genora.art 支持回复`,
    supportSignOff: "此致\nGenora.art 支持团队",
    topics: { cooperation: "合作伙伴关系", "billing-refund": "账单或退款", other: "其他问题", "inbound-email": "邮件咨询" },
  },
  hi: {
    ...en,
    verificationSubject: "Genora.art पंजीकरण की पुष्टि करें",
    verificationTitle: "अपना ईमेल पुष्टि करें",
    verificationBody: "पंजीकरण पूरा करने और मॉडल तक पहुँच पाने के लिए नीचे दिए बटन पर क्लिक करें।",
    verificationButton: "पंजीकरण पुष्टि करें",
    verificationFooter: "यह लिंक 24 घंटे तक मान्य है। यदि आपने खाता नहीं बनाया, तो इस ईमेल को अनदेखा करें।",
    verificationText: (url) => `Genora.art पंजीकरण पूरा करने के लिए ईमेल की पुष्टि करें: ${url}\n\nलिंक 24 घंटे तक मान्य है।`,
    supportReceiptSubject: (id) => `[${id}] हमें आपका अनुरोध मिला — Genora.art`,
    supportReceiptTitle: "हमें आपका अनुरोध मिला",
    supportReceiptDoNotReply: "कृपया इस ईमेल का उत्तर न दें।",
    supportReceiptTopic: "विषय",
    supportReceiptWorking: "हम आपके प्रश्न पर पहले से काम कर रहे हैं।",
    supportReceiptText: (id, topic, message) => `${id}. कृपया इस ईमेल का उत्तर न दें।\n\nहमें «${topic}» के बारे में अनुरोध मिला।\n\nआपका संदेश:\n${message}`,
    supportReplySubject: (id) => `[${id}] Genora.art सहायता का उत्तर`,
    supportSignOff: "सादर,\nGenora.art सहायता",
    topics: { cooperation: "साझेदारी", "billing-refund": "बिलिंग या धनवापसी", other: "अन्य", "inbound-email": "ईमेल से पूछताछ" },
  },
  es: {
    ...en,
    verificationSubject: "Confirma tu registro en Genora.art",
    verificationTitle: "Confirma tu correo",
    verificationBody: "Pulsa el botón para terminar el registro y acceder a los modelos.",
    verificationButton: "Confirmar registro",
    verificationFooter: "El enlace es válido 24 horas. Si no creaste una cuenta, ignora este correo.",
    verificationText: (url) => `Confirma tu correo para terminar el registro en Genora.art: ${url}\n\nEl enlace es válido 24 horas.`,
    supportReceiptSubject: (id) => `[${id}] Hemos recibido tu solicitud — Genora.art`,
    supportReceiptTitle: "Hemos recibido tu solicitud",
    supportReceiptDoNotReply: "No respondas a este correo.",
    supportReceiptTopic: "Tema",
    supportReceiptWorking: "Ya estamos atendiendo tu consulta.",
    supportReceiptText: (id, topic, message) => `${id}. No respondas a este correo.\n\nRecibimos una solicitud sobre «${topic}».\n\nTu mensaje:\n${message}`,
    supportReplySubject: (id) => `[${id}] Respuesta de soporte de Genora.art`,
    supportSignOff: "Un saludo,\nSoporte de Genora.art",
    topics: { cooperation: "Colaboración", "billing-refund": "Facturación o reembolso", other: "Otro asunto", "inbound-email": "Consulta por correo electrónico" },
  },
  fr: {
    ...en,
    verificationSubject: "Confirmez votre inscription à Genora.art",
    verificationTitle: "Confirmez votre e-mail",
    verificationBody: "Cliquez sur le bouton pour terminer l’inscription et accéder aux modèles.",
    verificationButton: "Confirmer l’inscription",
    verificationFooter: "Le lien est valable 24 heures. Si vous n’avez pas créé de compte, ignorez cet e-mail.",
    verificationText: (url) => `Confirmez votre e-mail pour terminer l’inscription à Genora.art : ${url}\n\nLe lien est valable 24 heures.`,
    supportReceiptSubject: (id) => `[${id}] Nous avons bien reçu votre demande — Genora.art`,
    supportReceiptTitle: "Nous avons bien reçu votre demande",
    supportReceiptDoNotReply: "Merci de ne pas répondre à cet e-mail.",
    supportReceiptTopic: "Sujet",
    supportReceiptWorking: "Nous traitons déjà votre question.",
    supportReceiptText: (id, topic, message) => `${id}. Merci de ne pas répondre à cet e-mail.\n\nNous avons reçu une demande au sujet de « ${topic} ».\n\nVotre message :\n${message}`,
    supportReplySubject: (id) => `[${id}] Réponse du support Genora.art`,
    supportSignOff: "Cordialement,\nSupport Genora.art",
    topics: { cooperation: "Partenariat", "billing-refund": "Facturation ou remboursement", other: "Autre demande", "inbound-email": "Demande par e-mail" },
  },
  ar: {
    ...en,
    verificationSubject: "أكد تسجيلك في Genora.art",
    verificationTitle: "أكد بريدك الإلكتروني",
    verificationBody: "اضغط الزر أدناه لإكمال التسجيل والوصول إلى النماذج.",
    verificationButton: "تأكيد التسجيل",
    verificationFooter: "الرابط صالح لمدة 24 ساعة. إذا لم تنشئ حسابًا، تجاهل هذه الرسالة.",
    verificationText: (url) => `أكد بريدك لإكمال التسجيل في Genora.art: ${url}\n\nالرابط صالح لمدة 24 ساعة.`,
    supportReceiptSubject: (id) => `[${id}] استلمنا طلبك — Genora.art`,
    supportReceiptTitle: "استلمنا طلبك",
    supportReceiptDoNotReply: "يرجى عدم الرد على هذه الرسالة.",
    supportReceiptTopic: "الموضوع",
    supportReceiptWorking: "نعمل بالفعل على سؤالك.",
    supportReceiptText: (id, topic, message) => `${id}. يرجى عدم الرد على هذه الرسالة.\n\nاستلمنا طلبًا حول «${topic}».\n\nرسالتك:\n${message}`,
    supportReplySubject: (id) => `[${id}] رد دعم Genora.art`,
    supportSignOff: "مع التحية،\nدعم Genora.art",
    topics: { cooperation: "التعاون", "billing-refund": "الفوترة أو استرداد الأموال", other: "موضوع آخر", "inbound-email": "استفسار عبر البريد الإلكتروني" },
  },
  pt: {
    ...en,
    verificationSubject: "Confirme o seu cadastro no Genora.art",
    verificationTitle: "Confirme o seu e-mail",
    verificationBody: "Clique no botão abaixo para concluir o cadastro e acessar os modelos.",
    verificationButton: "Confirmar cadastro",
    verificationFooter: "O link vale por 24 horas. Se você não criou uma conta, ignore este e-mail.",
    verificationText: (url) => `Confirme o e-mail para concluir o cadastro no Genora.art: ${url}\n\nO link vale por 24 horas.`,
    supportReceiptSubject: (id) => `[${id}] Recebemos o seu pedido — Genora.art`,
    supportReceiptTitle: "Recebemos o seu pedido",
    supportReceiptDoNotReply: "Não responda a este e-mail.",
    supportReceiptTopic: "Assunto",
    supportReceiptWorking: "Já estamos analisando a sua dúvida.",
    supportReceiptText: (id, topic, message) => `${id}. Não responda a este e-mail.\n\nRecebemos um pedido sobre “${topic}”.\n\nSua mensagem:\n${message}`,
    supportReplySubject: (id) => `[${id}] Resposta do suporte Genora.art`,
    supportSignOff: "Atenciosamente,\nSuporte Genora.art",
    topics: { cooperation: "Parceria", "billing-refund": "Cobrança ou reembolso", other: "Outro assunto", "inbound-email": "Consulta por e-mail" },
  },
  de: {
    ...en,
    verificationSubject: "Bestätigen Sie Ihre Genora.art-Registrierung",
    verificationTitle: "Bestätigen Sie Ihre E-Mail",
    verificationBody: "Klicken Sie auf die Schaltfläche, um die Registrierung abzuschließen und Modelle zu nutzen.",
    verificationButton: "Registrierung bestätigen",
    verificationFooter: "Der Link gilt 24 Stunden. Wenn Sie kein Konto erstellt haben, ignorieren Sie diese E-Mail.",
    verificationText: (url) => `Bestätigen Sie Ihre E-Mail, um die Genora.art-Registrierung abzuschließen: ${url}\n\nDer Link gilt 24 Stunden.`,
    supportReceiptSubject: (id) => `[${id}] Wir haben Ihre Anfrage erhalten — Genora.art`,
    supportReceiptTitle: "Wir haben Ihre Anfrage erhalten",
    supportReceiptDoNotReply: "Bitte antworten Sie nicht auf diese E-Mail.",
    supportReceiptTopic: "Thema",
    supportReceiptWorking: "Wir kümmern uns bereits um Ihre Frage.",
    supportReceiptText: (id, topic, message) => `${id}. Bitte antworten Sie nicht auf diese E-Mail.\n\nWir haben eine Anfrage zum Thema „${topic}“ erhalten.\n\nIhre Nachricht:\n${message}`,
    supportReplySubject: (id) => `[${id}] Antwort des Genora.art-Supports`,
    supportSignOff: "Mit freundlichen Grüßen\nGenora.art Support",
    topics: { cooperation: "Partnerschaft", "billing-refund": "Abrechnung oder Rückerstattung", other: "Anderes Anliegen", "inbound-email": "Anfrage per E-Mail" },
  },
  ja: {
    ...en,
    verificationSubject: "Genora.artの登録を確認してください",
    verificationTitle: "メールアドレスを確認",
    verificationBody: "下のボタンを押して登録を完了し、モデルをご利用ください。",
    verificationButton: "登録を確認",
    verificationFooter: "リンクの有効期限は24時間です。アカウントを作成していない場合は、このメールを無視してください。",
    verificationText: (url) => `Genora.artの登録を完了するにはメールを確認してください: ${url}\n\nリンクの有効期限は24時間です。`,
    supportReceiptSubject: (id) => `[${id}] お問い合わせを受け付けました — Genora.art`,
    supportReceiptTitle: "お問い合わせを受け付けました",
    supportReceiptDoNotReply: "このメールには返信しないでください。",
    supportReceiptTopic: "件名",
    supportReceiptWorking: "すでに対応を開始しています。",
    supportReceiptText: (id, topic, message) => `${id}。このメールには返信しないでください。\n\n「${topic}」についてのお問い合わせを受け付けました。\n\nメッセージ:\n${message}`,
    supportReplySubject: (id) => `[${id}] Genora.artサポートからの返信`,
    supportSignOff: "よろしくお願いいたします\nGenora.art サポート",
    topics: { cooperation: "提携について", "billing-refund": "請求または返金", other: "その他", "inbound-email": "メールでのお問い合わせ" },
  },
  it: {
    ...en,
    verificationSubject: "Conferma la registrazione a Genora.art",
    verificationTitle: "Conferma la tua email",
    verificationBody: "Clicca il pulsante per completare la registrazione e accedere ai modelli.",
    verificationButton: "Conferma registrazione",
    verificationFooter: "Il link è valido 24 ore. Se non hai creato un account, ignora questa email.",
    verificationText: (url) => `Conferma l’email per completare la registrazione a Genora.art: ${url}\n\nIl link è valido 24 ore.`,
    supportReceiptSubject: (id) => `[${id}] Abbiamo ricevuto la tua richiesta — Genora.art`,
    supportReceiptTitle: "Abbiamo ricevuto la tua richiesta",
    supportReceiptDoNotReply: "Non rispondere a questa email.",
    supportReceiptTopic: "Argomento",
    supportReceiptWorking: "Stiamo già esaminando la tua domanda.",
    supportReceiptText: (id, topic, message) => `${id}. Non rispondere a questa email.\n\nAbbiamo ricevuto una richiesta su «${topic}».\n\nIl tuo messaggio:\n${message}`,
    supportReplySubject: (id) => `[${id}] Risposta del supporto Genora.art`,
    supportSignOff: "Cordiali saluti,\nSupporto Genora.art",
    topics: { cooperation: "Collaborazione", "billing-refund": "Fatturazione o rimborso", other: "Altro", "inbound-email": "Richiesta via email" },
  },
  ko: {
    ...en,
    verificationSubject: "Genora.art 가입을 확인해 주세요",
    verificationTitle: "이메일을 확인하세요",
    verificationBody: "아래 버튼을 눌러 가입을 완료하고 모델을 이용하세요.",
    verificationButton: "가입 확인",
    verificationFooter: "링크는 24시간 동안 유효합니다. 계정을 만들지 않으셨다면 이 메일을 무시하세요.",
    verificationText: (url) => `Genora.art 가입을 완료하려면 이메일을 확인하세요: ${url}\n\n링크는 24시간 동안 유효합니다.`,
    supportReceiptSubject: (id) => `[${id}] 문의가 접수되었습니다 — Genora.art`,
    supportReceiptTitle: "문의가 접수되었습니다",
    supportReceiptDoNotReply: "이 메일에 답장하지 마세요.",
    supportReceiptTopic: "주제",
    supportReceiptWorking: "이미 문의 내용을 확인하고 있습니다.",
    supportReceiptText: (id, topic, message) => `${id}. 이 메일에 답장하지 마세요.\n\n「${topic}」 관련 문의를 받았습니다.\n\n메시지:\n${message}`,
    supportReplySubject: (id) => `[${id}] Genora.art 지원 답변`,
    supportSignOff: "감사합니다.\nGenora.art 지원팀",
    topics: { cooperation: "제휴", "billing-refund": "결제 또는 환불", other: "기타 문의", "inbound-email": "이메일 문의" },
  },
  tr: {
    ...en,
    verificationSubject: "Genora.art kaydınızı doğrulayın",
    verificationTitle: "E-postanızı doğrulayın",
    verificationBody: "Kaydı tamamlamak ve modellere erişmek için aşağıdaki düğmeye tıklayın.",
    verificationButton: "Kaydı doğrula",
    verificationFooter: "Bağlantı 24 saat geçerlidir. Hesap oluşturmadıysanız bu e-postayı yok sayın.",
    verificationText: (url) => `Genora.art kaydını tamamlamak için e-postanızı doğrulayın: ${url}\n\nBağlantı 24 saat geçerlidir.`,
    supportReceiptSubject: (id) => `[${id}] Talebinizi aldık — Genora.art`,
    supportReceiptTitle: "Talebinizi aldık",
    supportReceiptDoNotReply: "Lütfen bu e-postayı yanıtlamayın.",
    supportReceiptTopic: "Konu",
    supportReceiptWorking: "Sorunuzla zaten ilgileniyoruz.",
    supportReceiptText: (id, topic, message) => `${id}. Lütfen bu e-postayı yanıtlamayın.\n\n“${topic}” hakkında bir talep aldık.\n\nMesajınız:\n${message}`,
    supportReplySubject: (id) => `[${id}] Genora.art destek yanıtı`,
    supportSignOff: "Saygılarımızla,\nGenora.art Destek",
    topics: { cooperation: "İş birliği", "billing-refund": "Faturalandırma veya iade", other: "Diğer", "inbound-email": "E-posta ile soru" },
  },
  pl: {
    ...en,
    verificationSubject: "Potwierdź rejestrację w Genora.art",
    verificationTitle: "Potwierdź swój e-mail",
    verificationBody: "Kliknij przycisk, aby dokończyć rejestrację i uzyskać dostęp do modeli.",
    verificationButton: "Potwierdź rejestrację",
    verificationFooter: "Link jest ważny 24 godziny. Jeśli nie zakładałeś konta, zignoruj tę wiadomość.",
    verificationText: (url) => `Potwierdź e-mail, aby dokończyć rejestrację w Genora.art: ${url}\n\nLink jest ważny 24 godziny.`,
    supportReceiptSubject: (id) => `[${id}] Otrzymaliśmy Twoje zgłoszenie — Genora.art`,
    supportReceiptTitle: "Otrzymaliśmy Twoje zgłoszenie",
    supportReceiptDoNotReply: "Nie odpowiadaj na tę wiadomość.",
    supportReceiptTopic: "Temat",
    supportReceiptWorking: "Już zajmujemy się Twoim pytaniem.",
    supportReceiptText: (id, topic, message) => `${id}. Nie odpowiadaj na tę wiadomość.\n\nOtrzymaliśmy zgłoszenie w sprawie „${topic}”.\n\nTwoja wiadomość:\n${message}`,
    supportReplySubject: (id) => `[${id}] Odpowiedź wsparcia Genora.art`,
    supportSignOff: "Pozdrawiamy,\nWsparcie Genora.art",
    topics: { cooperation: "Współpraca", "billing-refund": "Płatności lub zwroty", other: "Inna sprawa", "inbound-email": "Zapytanie e-mailowe" },
  },
  nl: {
    ...en,
    verificationSubject: "Bevestig je Genora.art-registratie",
    verificationTitle: "Bevestig je e-mail",
    verificationBody: "Klik op de knop om de registratie af te ronden en toegang tot de modellen te krijgen.",
    verificationButton: "Registratie bevestigen",
    verificationFooter: "De link is 24 uur geldig. Als je geen account hebt gemaakt, kun je deze e-mail negeren.",
    verificationText: (url) => `Bevestig je e-mail om de Genora.art-registratie af te ronden: ${url}\n\nDe link is 24 uur geldig.`,
    supportReceiptSubject: (id) => `[${id}] We hebben je verzoek ontvangen — Genora.art`,
    supportReceiptTitle: "We hebben je verzoek ontvangen",
    supportReceiptDoNotReply: "Beantwoord deze e-mail niet.",
    supportReceiptTopic: "Onderwerp",
    supportReceiptWorking: "We zijn al met je vraag bezig.",
    supportReceiptText: (id, topic, message) => `${id}. Beantwoord deze e-mail niet.\n\nWe ontvingen een verzoek over “${topic}”.\n\nJe bericht:\n${message}`,
    supportReplySubject: (id) => `[${id}] Antwoord van Genora.art-support`,
    supportSignOff: "Met vriendelijke groet,\nGenora.art Support",
    topics: { cooperation: "Samenwerking", "billing-refund": "Facturering of terugbetaling", other: "Andere vraag", "inbound-email": "Vraag per e-mail" },
  },
  sv: {
    ...en,
    verificationSubject: "Bekräfta din Genora.art-registrering",
    verificationTitle: "Bekräfta din e-post",
    verificationBody: "Klicka på knappen för att slutföra registreringen och få tillgång till modellerna.",
    verificationButton: "Bekräfta registrering",
    verificationFooter: "Länken gäller i 24 timmar. Om du inte skapade ett konto kan du ignorera mejlet.",
    verificationText: (url) => `Bekräfta din e-post för att slutföra Genora.art-registreringen: ${url}\n\nLänken gäller i 24 timmar.`,
    supportReceiptSubject: (id) => `[${id}] Vi har tagit emot din förfrågan — Genora.art`,
    supportReceiptTitle: "Vi har tagit emot din förfrågan",
    supportReceiptDoNotReply: "Svara inte på det här mejlet.",
    supportReceiptTopic: "Ämne",
    supportReceiptWorking: "Vi tittar redan på din fråga.",
    supportReceiptText: (id, topic, message) => `${id}. Svara inte på det här mejlet.\n\nVi har tagit emot en förfrågan om “${topic}”.\n\nDitt meddelande:\n${message}`,
    supportReplySubject: (id) => `[${id}] Svar från Genora.art-support`,
    supportSignOff: "Med vänliga hälsningar,\nGenora.art Support",
    topics: { cooperation: "Samarbete", "billing-refund": "Fakturering eller återbetalning", other: "Annat ärende", "inbound-email": "E-postförfrågan" },
  },
  cs: {
    ...en,
    verificationSubject: "Potvrďte registraci v Genora.art",
    verificationTitle: "Potvrďte e-mail",
    verificationBody: "Klikněte na tlačítko a dokončete registraci, abyste získali přístup k modelům.",
    verificationButton: "Potvrdit registraci",
    verificationFooter: "Odkaz platí 24 hodin. Pokud jste účet nevytvořili, e-mail ignorujte.",
    verificationText: (url) => `Potvrďte e-mail a dokončete registraci v Genora.art: ${url}\n\nOdkaz platí 24 hodin.`,
    supportReceiptSubject: (id) => `[${id}] Obdrželi jsme váš požadavek — Genora.art`,
    supportReceiptTitle: "Obdrželi jsme váš požadavek",
    supportReceiptDoNotReply: "Na tento e-mail neodpovídejte.",
    supportReceiptTopic: "Téma",
    supportReceiptWorking: "Vaším dotazem se už zabýváme.",
    supportReceiptText: (id, topic, message) => `${id}. Na tento e-mail neodpovídejte.\n\nObdrželi jsme požadavek na téma „${topic}“.\n\nVaše zpráva:\n${message}`,
    supportReplySubject: (id) => `[${id}] Odpověď podpory Genora.art`,
    supportSignOff: "S pozdravem\nPodpora Genora.art",
    topics: { cooperation: "Spolupráce", "billing-refund": "Platba nebo vrácení peněz", other: "Jiný dotaz", "inbound-email": "Dotaz e-mailem" },
  },
  el: {
    ...en,
    verificationSubject: "Επιβεβαιώστε την εγγραφή σας στο Genora.art",
    verificationTitle: "Επιβεβαιώστε το email σας",
    verificationBody: "Πατήστε το κουμπί για να ολοκληρώσετε την εγγραφή και να αποκτήσετε πρόσβαση στα μοντέλα.",
    verificationButton: "Επιβεβαίωση εγγραφής",
    verificationFooter: "Ο σύνδεσμος ισχύει για 24 ώρες. Αν δεν δημιουργήσατε λογαριασμό, αγνοήστε αυτό το μήνυμα.",
    verificationText: (url) => `Επιβεβαιώστε το email για να ολοκληρώσετε την εγγραφή στο Genora.art: ${url}\n\nΟ σύνδεσμος ισχύει για 24 ώρες.`,
    supportReceiptSubject: (id) => `[${id}] Λάβαμε το αίτημά σας — Genora.art`,
    supportReceiptTitle: "Λάβαμε το αίτημά σας",
    supportReceiptDoNotReply: "Μην απαντήσετε σε αυτό το email.",
    supportReceiptTopic: "Θέμα",
    supportReceiptWorking: "Ήδη ασχολούμαστε με την ερώτησή σας.",
    supportReceiptText: (id, topic, message) => `${id}. Μην απαντήσετε σε αυτό το email.\n\nΛάβαμε αίτημα σχετικά με «${topic}».\n\nΤο μήνυμά σας:\n${message}`,
    supportReplySubject: (id) => `[${id}] Απάντηση υποστήριξης Genora.art`,
    supportSignOff: "Με εκτίμηση,\nΥποστήριξη Genora.art",
    topics: { cooperation: "Συνεργασία", "billing-refund": "Χρέωση ή επιστροφή χρημάτων", other: "Άλλο θέμα", "inbound-email": "Ερώτημα μέσω email" },
  },
  ro: {
    ...en,
    verificationSubject: "Confirmă înregistrarea în Genora.art",
    verificationTitle: "Confirmă adresa de e-mail",
    verificationBody: "Apasă butonul pentru a finaliza înregistrarea și a accesa modelele.",
    verificationButton: "Confirmă înregistrarea",
    verificationFooter: "Linkul este valabil 24 de ore. Dacă nu ai creat un cont, ignoră acest e-mail.",
    verificationText: (url) => `Confirmă e-mailul pentru a finaliza înregistrarea în Genora.art: ${url}\n\nLinkul este valabil 24 de ore.`,
    supportReceiptSubject: (id) => `[${id}] Am primit solicitarea ta — Genora.art`,
    supportReceiptTitle: "Am primit solicitarea ta",
    supportReceiptDoNotReply: "Te rugăm să nu răspunzi la acest e-mail.",
    supportReceiptTopic: "Subiect",
    supportReceiptWorking: "Ne ocupăm deja de întrebarea ta.",
    supportReceiptText: (id, topic, message) => `${id}. Te rugăm să nu răspunzi la acest e-mail.\n\nAm primit o solicitare despre „${topic}”.\n\nMesajul tău:\n${message}`,
    supportReplySubject: (id) => `[${id}] Răspunsul suportului Genora.art`,
    supportSignOff: "Cu stimă,\nSuport Genora.art",
    topics: { cooperation: "Colaborare", "billing-refund": "Facturare sau rambursare", other: "Altă solicitare", "inbound-email": "Solicitare prin e-mail" },
  },
};

export function getMailCopy(locale?: string | null): MailCopy {
  if (locale && copies[locale as Locale]) return copies[locale as Locale]!;
  return copies.en ?? ru;
}

export function supportTopicLabel(topic: string, locale?: string | null): string {
  const copy = getMailCopy(locale);
  return copy.topics[topic] ?? topic;
}
