import { formatTokensAsCredits } from "./credits";
import type { Locale } from "./i18n/types";

const LOCALES: readonly Locale[] = [
  "ru", "en", "zh", "hi", "es", "fr", "ar", "pt", "de", "ja", "it", "ko", "tr", "pl", "nl", "sv", "cs", "el", "ro",
];

const intlByLocale: Record<Locale, string> = {
  ru: "ru-RU",
  en: "en-US",
  zh: "zh-CN",
  hi: "hi-IN",
  es: "es-ES",
  fr: "fr-FR",
  ar: "ar-SA",
  pt: "pt-BR",
  de: "de-DE",
  ja: "ja-JP",
  it: "it-IT",
  ko: "ko-KR",
  tr: "tr-TR",
  pl: "pl-PL",
  nl: "nl-NL",
  sv: "sv-SE",
  cs: "cs-CZ",
  el: "el-GR",
  ro: "ro-RO",
};

export function usageHistoryLocale(value?: string | null): Locale {
  return value && (LOCALES as readonly string[]).includes(value) ? value as Locale : "ru";
}

export type UsageHistoryCopy = {
  noAgent: string;
  starterBalance: string;
  registrationBonus: string;
  studyAttachment: string;
  reviewAttachment: string;
  newImageConversation: string;
  imagePromptFallback: string;
  imageAgentFallback: string;
  newBattle: string;
  usageNote: (model: string) => string;
  imageGeneration: (model: string) => string;
  imageComment: (count: number) => string;
  imageCommentWithAgent: (agent: string, count: number) => string;
  battleChatTitle: (prompt: string) => string;
  bonus: (tokens: number) => string;
  agentHelp: string;
};

type UsageHistoryTemplates = {
  noAgent: string;
  starterBalance: string;
  registrationBonus: string;
  studyAttachment: string;
  reviewAttachment: string;
  newImageConversation: string;
  imagePromptFallback: string;
  imageAgentFallback: string;
  newBattle: string;
  usageNote: string;
  imageGeneration: string;
  imageComment: string;
  imageCommentWithAgent: string;
  battleChatTitle: string;
  battleChatTitleEmpty: string;
  bonus: string;
  agentHelp: string;
};

const templates: Record<Locale, UsageHistoryTemplates> = {
  ru: {
    noAgent: "Без агента",
    starterBalance: "Стартовый баланс",
    registrationBonus: "Бонус за регистрацию",
    studyAttachment: "Вложение",
    reviewAttachment: "Пожалуйста, изучи вложение.",
    newImageConversation: "Новая генерация",
    imagePromptFallback: "Генерация изображения",
    imageAgentFallback: "Генерация изображений",
    newBattle: "Новая битва",
    usageNote: "Использование {model}",
    imageGeneration: "Генерация {model}",
    imageComment: "Изображения ИИ · {count} вар.",
    imageCommentWithAgent: "Изображения ИИ · {agent} · {count} вар.",
    battleChatTitle: "Битва моделей: {prompt}",
    battleChatTitleEmpty: "Битва моделей",
    bonus: "Бонус — {tokens} токенов",
    agentHelp: "Помощь в создании агента",
  },
  en: {
    noAgent: "No agent",
    starterBalance: "Starting balance",
    registrationBonus: "Sign-up bonus",
    studyAttachment: "Attachment",
    reviewAttachment: "Please review the attachment.",
    newImageConversation: "New generation",
    imagePromptFallback: "Image generation",
    imageAgentFallback: "Image generation",
    newBattle: "New battle",
    usageNote: "Usage {model}",
    imageGeneration: "Generation {model}",
    imageComment: "AI images · {count} var.",
    imageCommentWithAgent: "AI images · {agent} · {count} var.",
    battleChatTitle: "Model battle: {prompt}",
    battleChatTitleEmpty: "Model battle",
    bonus: "Bonus — {tokens} tokens",
    agentHelp: "Help creating an agent",
  },
  zh: {
    noAgent: "无智能体",
    starterBalance: "起始余额",
    registrationBonus: "注册奖励",
    studyAttachment: "附件",
    reviewAttachment: "请查看附件。",
    newImageConversation: "新的生成",
    imagePromptFallback: "图像生成",
    imageAgentFallback: "图像生成",
    newBattle: "新对战",
    usageNote: "使用 {model}",
    imageGeneration: "生成 {model}",
    imageComment: "AI 图像 · {count} 变体",
    imageCommentWithAgent: "AI 图像 · {agent} · {count} 变体",
    battleChatTitle: "模型对战：{prompt}",
    battleChatTitleEmpty: "模型对战",
    bonus: "奖励 — {tokens} 代币",
    agentHelp: "协助创建智能体",
  },
  hi: {
    noAgent: "कोई एजेंट नहीं",
    starterBalance: "शुरुआती शेष",
    registrationBonus: "पंजीकरण बोनस",
    studyAttachment: "अटैचमेंट",
    reviewAttachment: "कृपया अटैचमेंट देखें.",
    newImageConversation: "नई जनरेशन",
    imagePromptFallback: "छवि जनरेशन",
    imageAgentFallback: "छवि जनरेशन",
    newBattle: "नई लड़ाई",
    usageNote: "उपयोग {model}",
    imageGeneration: "जनरेशन {model}",
    imageComment: "AI छवियाँ · {count} रूप",
    imageCommentWithAgent: "AI छवियाँ · {agent} · {count} रूप",
    battleChatTitle: "मॉडल लड़ाई: {prompt}",
    battleChatTitleEmpty: "मॉडल लड़ाई",
    bonus: "बोनस — {tokens} टोकन",
    agentHelp: "एजेंट बनाने में मदद",
  },
  es: {
    noAgent: "Sin agente",
    starterBalance: "Saldo inicial",
    registrationBonus: "Bono de registro",
    studyAttachment: "Archivo adjunto",
    reviewAttachment: "Revisa el archivo adjunto.",
    newImageConversation: "Nueva generación",
    imagePromptFallback: "Generación de imagen",
    imageAgentFallback: "Generación de imágenes",
    newBattle: "Nueva batalla",
    usageNote: "Uso {model}",
    imageGeneration: "Generación {model}",
    imageComment: "Imágenes IA · {count} var.",
    imageCommentWithAgent: "Imágenes IA · {agent} · {count} var.",
    battleChatTitle: "Batalla de modelos: {prompt}",
    battleChatTitleEmpty: "Batalla de modelos",
    bonus: "Bono — {tokens} tokens",
    agentHelp: "Ayuda para crear un agente",
  },
  fr: {
    noAgent: "Sans agent",
    starterBalance: "Solde de départ",
    registrationBonus: "Bonus d’inscription",
    studyAttachment: "Pièce jointe",
    reviewAttachment: "Merci d’examiner la pièce jointe.",
    newImageConversation: "Nouvelle génération",
    imagePromptFallback: "Génération d’image",
    imageAgentFallback: "Génération d’images",
    newBattle: "Nouveau duel",
    usageNote: "Utilisation {model}",
    imageGeneration: "Génération {model}",
    imageComment: "Images IA · {count} var.",
    imageCommentWithAgent: "Images IA · {agent} · {count} var.",
    battleChatTitle: "Duel de modèles : {prompt}",
    battleChatTitleEmpty: "Duel de modèles",
    bonus: "Bonus — {tokens} jetons",
    agentHelp: "Aide à la création d’un agent",
  },
  ar: {
    noAgent: "بدون وكيل",
    starterBalance: "الرصيد الابتدائي",
    registrationBonus: "مكافأة التسجيل",
    studyAttachment: "مرفق",
    reviewAttachment: "يرجى مراجعة المرفق.",
    newImageConversation: "توليد جديد",
    imagePromptFallback: "توليد صورة",
    imageAgentFallback: "توليد الصور",
    newBattle: "معركة جديدة",
    usageNote: "استخدام {model}",
    imageGeneration: "توليد {model}",
    imageComment: "صور الذكاء الاصطناعي · {count} نسخة",
    imageCommentWithAgent: "صور الذكاء الاصطناعي · {agent} · {count} نسخة",
    battleChatTitle: "معركة النماذج: {prompt}",
    battleChatTitleEmpty: "معركة النماذج",
    bonus: "مكافأة — {tokens} رمزًا",
    agentHelp: "المساعدة في إنشاء وكيل",
  },
  pt: {
    noAgent: "Sem agente",
    starterBalance: "Saldo inicial",
    registrationBonus: "Bônus de cadastro",
    studyAttachment: "Anexo",
    reviewAttachment: "Revise o anexo.",
    newImageConversation: "Nova geração",
    imagePromptFallback: "Geração de imagem",
    imageAgentFallback: "Geração de imagens",
    newBattle: "Nova batalha",
    usageNote: "Uso {model}",
    imageGeneration: "Geração {model}",
    imageComment: "Imagens IA · {count} var.",
    imageCommentWithAgent: "Imagens IA · {agent} · {count} var.",
    battleChatTitle: "Batalha de modelos: {prompt}",
    battleChatTitleEmpty: "Batalha de modelos",
    bonus: "Bônus — {tokens} tokens",
    agentHelp: "Ajuda para criar um agente",
  },
  de: {
    noAgent: "Kein Agent",
    starterBalance: "Startguthaben",
    registrationBonus: "Bonus für die Registrierung",
    studyAttachment: "Anhang",
    reviewAttachment: "Bitte prüfe den Anhang.",
    newImageConversation: "Neue Generierung",
    imagePromptFallback: "Bildgenerierung",
    imageAgentFallback: "Bildgenerierung",
    newBattle: "Neuer Kampf",
    usageNote: "Nutzung {model}",
    imageGeneration: "Generierung {model}",
    imageComment: "KI-Bilder · {count} Var.",
    imageCommentWithAgent: "KI-Bilder · {agent} · {count} Var.",
    battleChatTitle: "Modellkampf: {prompt}",
    battleChatTitleEmpty: "Modellkampf",
    bonus: "Bonus — {tokens} Token",
    agentHelp: "Hilfe beim Erstellen eines Agenten",
  },
  ja: {
    noAgent: "エージェントなし",
    starterBalance: "初期残高",
    registrationBonus: "登録ボーナス",
    studyAttachment: "添付ファイル",
    reviewAttachment: "添付ファイルを確認してください。",
    newImageConversation: "新しい生成",
    imagePromptFallback: "画像生成",
    imageAgentFallback: "画像生成",
    newBattle: "新しい対戦",
    usageNote: "利用 {model}",
    imageGeneration: "生成 {model}",
    imageComment: "AI画像 · {count} バリエーション",
    imageCommentWithAgent: "AI画像 · {agent} · {count} バリエーション",
    battleChatTitle: "モデル対戦: {prompt}",
    battleChatTitleEmpty: "モデル対戦",
    bonus: "ボーナス — {tokens} トークン",
    agentHelp: "エージェント作成のサポート",
  },
  it: {
    noAgent: "Nessun agente",
    starterBalance: "Saldo iniziale",
    registrationBonus: "Bonus di registrazione",
    studyAttachment: "Allegato",
    reviewAttachment: "Controlla l’allegato.",
    newImageConversation: "Nuova generazione",
    imagePromptFallback: "Generazione immagine",
    imageAgentFallback: "Generazione immagini",
    newBattle: "Nuova battaglia",
    usageNote: "Utilizzo {model}",
    imageGeneration: "Generazione {model}",
    imageComment: "Immagini IA · {count} var.",
    imageCommentWithAgent: "Immagini IA · {agent} · {count} var.",
    battleChatTitle: "Battaglia modelli: {prompt}",
    battleChatTitleEmpty: "Battaglia modelli",
    bonus: "Bonus — {tokens} token",
    agentHelp: "Aiuto per creare un agente",
  },
  ko: {
    noAgent: "에이전트 없음",
    starterBalance: "시작 잔액",
    registrationBonus: "가입 보너스",
    studyAttachment: "첨부 파일",
    reviewAttachment: "첨부 파일을 확인해 주세요.",
    newImageConversation: "새 생성",
    imagePromptFallback: "이미지 생성",
    imageAgentFallback: "이미지 생성",
    newBattle: "새 배틀",
    usageNote: "사용 {model}",
    imageGeneration: "생성 {model}",
    imageComment: "AI 이미지 · {count}개",
    imageCommentWithAgent: "AI 이미지 · {agent} · {count}개",
    battleChatTitle: "모델 배틀: {prompt}",
    battleChatTitleEmpty: "모델 배틀",
    bonus: "보너스 — {tokens} 토큰",
    agentHelp: "에이전트 만들기 도움",
  },
  tr: {
    noAgent: "Ajan yok",
    starterBalance: "Başlangıç bakiyesi",
    registrationBonus: "Kayıt bonusu",
    studyAttachment: "Ek",
    reviewAttachment: "Lütfen eki incele.",
    newImageConversation: "Yeni üretim",
    imagePromptFallback: "Görsel üretimi",
    imageAgentFallback: "Görsel üretimi",
    newBattle: "Yeni savaş",
    usageNote: "Kullanım {model}",
    imageGeneration: "Üretim {model}",
    imageComment: "AI görselleri · {count} var.",
    imageCommentWithAgent: "AI görselleri · {agent} · {count} var.",
    battleChatTitle: "Model savaşı: {prompt}",
    battleChatTitleEmpty: "Model savaşı",
    bonus: "Bonus — {tokens} jeton",
    agentHelp: "Ajan oluşturma yardımı",
  },
  pl: {
    noAgent: "Brak agenta",
    starterBalance: "Saldo startowe",
    registrationBonus: "Bonus za rejestrację",
    studyAttachment: "Załącznik",
    reviewAttachment: "Sprawdź załącznik.",
    newImageConversation: "Nowa generacja",
    imagePromptFallback: "Generowanie obrazu",
    imageAgentFallback: "Generowanie obrazów",
    newBattle: "Nowa bitwa",
    usageNote: "Użycie {model}",
    imageGeneration: "Generacja {model}",
    imageComment: "Obrazy AI · {count} war.",
    imageCommentWithAgent: "Obrazy AI · {agent} · {count} war.",
    battleChatTitle: "Bitwa modeli: {prompt}",
    battleChatTitleEmpty: "Bitwa modeli",
    bonus: "Bonus — {tokens} tokenów",
    agentHelp: "Pomoc w tworzeniu agenta",
  },
  nl: {
    noAgent: "Geen agent",
    starterBalance: "Startsaldo",
    registrationBonus: "Bonus bij registratie",
    studyAttachment: "Bijlage",
    reviewAttachment: "Bekijk de bijlage.",
    newImageConversation: "Nieuwe generatie",
    imagePromptFallback: "Beeldgeneratie",
    imageAgentFallback: "Beeldgeneratie",
    newBattle: "Nieuw gevecht",
    usageNote: "Gebruik {model}",
    imageGeneration: "Generatie {model}",
    imageComment: "AI-beelden · {count} var.",
    imageCommentWithAgent: "AI-beelden · {agent} · {count} var.",
    battleChatTitle: "Modelgevecht: {prompt}",
    battleChatTitleEmpty: "Modelgevecht",
    bonus: "Bonus — {tokens} tokens",
    agentHelp: "Hulp bij het maken van een agent",
  },
  sv: {
    noAgent: "Ingen agent",
    starterBalance: "Startsaldo",
    registrationBonus: "Registreringsbonus",
    studyAttachment: "Bilaga",
    reviewAttachment: "Granska bilagan.",
    newImageConversation: "Ny generering",
    imagePromptFallback: "Bildgenerering",
    imageAgentFallback: "Bildgenerering",
    newBattle: "Ny strid",
    usageNote: "Användning {model}",
    imageGeneration: "Generering {model}",
    imageComment: "AI-bilder · {count} var.",
    imageCommentWithAgent: "AI-bilder · {agent} · {count} var.",
    battleChatTitle: "Modellstrid: {prompt}",
    battleChatTitleEmpty: "Modellstrid",
    bonus: "Bonus — {tokens} token",
    agentHelp: "Hjälp att skapa en agent",
  },
  cs: {
    noAgent: "Bez agenta",
    starterBalance: "Počáteční zůstatek",
    registrationBonus: "Bonus za registraci",
    studyAttachment: "Příloha",
    reviewAttachment: "Prosím, podívej se na přílohu.",
    newImageConversation: "Nová generace",
    imagePromptFallback: "Generování obrázku",
    imageAgentFallback: "Generování obrázků",
    newBattle: "Nová bitva",
    usageNote: "Použití {model}",
    imageGeneration: "Generace {model}",
    imageComment: "AI obrázky · {count} var.",
    imageCommentWithAgent: "AI obrázky · {agent} · {count} var.",
    battleChatTitle: "Bitva modelů: {prompt}",
    battleChatTitleEmpty: "Bitva modelů",
    bonus: "Bonus — {tokens} tokenů",
    agentHelp: "Pomoc s vytvořením agenta",
  },
  el: {
    noAgent: "Χωρίς πράκτορα",
    starterBalance: "Αρχικό υπόλοιπο",
    registrationBonus: "Μπόνους εγγραφής",
    studyAttachment: "Συνημμένο",
    reviewAttachment: "Ελέγξτε το συνημμένο.",
    newImageConversation: "Νέα δημιουργία",
    imagePromptFallback: "Δημιουργία εικόνας",
    imageAgentFallback: "Δημιουργία εικόνων",
    newBattle: "Νέα μάχη",
    usageNote: "Χρήση {model}",
    imageGeneration: "Δημιουργία {model}",
    imageComment: "Εικόνες AI · {count} παραλ.",
    imageCommentWithAgent: "Εικόνες AI · {agent} · {count} παραλ.",
    battleChatTitle: "Μάχη μοντέλων: {prompt}",
    battleChatTitleEmpty: "Μάχη μοντέλων",
    bonus: "Μπόνους — {tokens} μάρκες",
    agentHelp: "Βοήθεια δημιουργίας πράκτορα",
  },
  ro: {
    noAgent: "Fără agent",
    starterBalance: "Sold inițial",
    registrationBonus: "Bonus de înregistrare",
    studyAttachment: "Atașament",
    reviewAttachment: "Te rog verifică atașamentul.",
    newImageConversation: "Generare nouă",
    imagePromptFallback: "Generare de imagine",
    imageAgentFallback: "Generare de imagini",
    newBattle: "Luptă nouă",
    usageNote: "Utilizare {model}",
    imageGeneration: "Generare {model}",
    imageComment: "Imagini IA · {count} var.",
    imageCommentWithAgent: "Imagini IA · {agent} · {count} var.",
    battleChatTitle: "Luptă de modele: {prompt}",
    battleChatTitleEmpty: "Luptă de modele",
    bonus: "Bonus — {tokens} jetoane",
    agentHelp: "Ajutor la crearea unui agent",
  },
};

function fill(template: string, values: Record<string, string | number>): string {
  return template.replace(/\{(\w+)\}/g, (_, key: string) => String(values[key] ?? ""));
}

export function usageHistoryCopy(locale?: string | null): UsageHistoryCopy {
  const code = usageHistoryLocale(locale);
  const item = templates[code];
  const intl = intlByLocale[code];
  return {
    noAgent: item.noAgent,
    starterBalance: item.starterBalance,
    registrationBonus: item.registrationBonus,
    studyAttachment: item.studyAttachment,
    reviewAttachment: item.reviewAttachment,
    newImageConversation: item.newImageConversation,
    imagePromptFallback: item.imagePromptFallback,
    imageAgentFallback: item.imageAgentFallback,
    newBattle: item.newBattle,
    usageNote: (model) => fill(item.usageNote, { model }),
    imageGeneration: (model) => fill(item.imageGeneration, { model }),
    imageComment: (count) => fill(item.imageComment, { count }),
    imageCommentWithAgent: (agent, count) => fill(item.imageCommentWithAgent, { agent, count }),
    battleChatTitle: (prompt) => {
      const trimmed = prompt.replace(/[\n\r]+/g, " ").trim();
      return trimmed ? fill(item.battleChatTitle, { prompt: trimmed.slice(0, 120) }) : item.battleChatTitleEmpty;
    },
    bonus: (tokens) => `${item.bonus.split("{tokens}")[0]}${formatTokensAsCredits(tokens, intl, "spend")}`,
    agentHelp: item.agentHelp,
  };
}

export const PERSIST_USER_LOCALE_SQL = "UPDATE users SET locale=$2, updated_at=now() WHERE id=$1 AND locale IS DISTINCT FROM $2";
