"use client";

import { useLocale } from "@/components/providers/locale-provider";
import { authUiCopy } from "@/lib/i18n/copy/auth-ui";
import { Loader2, LockKeyhole } from "lucide-react";
import { useState, type FormEvent } from "react";

export default function PreviewLoginPage() {
  const {locale}=useLocale();const copy=authUiCopy(locale).preview;
  const [username,setUsername]=useState("");const [password,setPassword]=useState("");const [remember,setRemember]=useState(true);const [busy,setBusy]=useState(false);const [error,setError]=useState<string|null>(null);
  const submit=async(event:FormEvent)=>{event.preventDefault();setBusy(true);setError(null);const response=await fetch("/api/preview/session",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({username,password,remember})}).catch(()=>null);const payload=response?await response.json().catch(()=>null) as {error?:string}|null:null;if(!response?.ok){setError(payload?.error??copy.failed);setBusy(false);return;}const next=new URLSearchParams(window.location.search).get("next");window.location.replace(next?.startsWith("/")&&!next.startsWith("//")?next:"/");};
  return <main className="grid min-h-dvh place-items-center bg-[#08111d] px-4 text-white"><form onSubmit={submit} className="w-full max-w-sm rounded-3xl border border-white/10 bg-[#0f1b2b] p-7 shadow-2xl"><span className="grid size-12 place-items-center rounded-2xl bg-blue-500/15 text-blue-400"><LockKeyhole className="size-6"/></span><h1 className="mt-5 text-2xl font-semibold">Genora.art Preview</h1><p className="mt-2 text-sm text-slate-400">{copy.subtitle}</p><label className="mt-6 grid gap-2 text-sm text-slate-300">{copy.username}<input required autoComplete="username" value={username} onChange={event=>setUsername(event.target.value)} className="h-11 rounded-xl border border-white/10 bg-[#08111d] px-3 outline-none focus:border-blue-500"/></label><label className="mt-4 grid gap-2 text-sm text-slate-300">{copy.password}<input required type="password" autoComplete="current-password" value={password} onChange={event=>setPassword(event.target.value)} className="h-11 rounded-xl border border-white/10 bg-[#08111d] px-3 outline-none focus:border-blue-500"/></label><label className="mt-4 flex items-center gap-2 text-sm text-slate-300"><input type="checkbox" checked={remember} onChange={event=>setRemember(event.target.checked)} className="size-4 accent-blue-500"/>{copy.remember}</label>{error?<p className="mt-4 rounded-xl bg-red-500/10 px-3 py-2 text-sm text-red-300">{error}</p>:null}<button disabled={busy} className="mt-6 inline-flex h-11 w-full items-center justify-center gap-2 rounded-xl bg-blue-500 font-semibold hover:bg-blue-400 disabled:opacity-50">{busy?<Loader2 className="size-4 animate-spin"/>:null}{copy.signIn}</button></form></main>;
}
